"""
낙화검심 v0.6 - 소모품 50종 (귀환서 포함)
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from app.core.database import SessionLocal, engine, Base
from app.models import Item

def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    if db.query(Item).filter(Item.code == "CONS_RETURN_SCROLL").count() > 0:
        print("v6 consumables already seeded!"); db.close(); return

    consumables = [    {"id": 3000, "code": "CONS_RETURN_SCROLL", "name": "귀환서", "item_type": "consumable", "sub_type": "소모품", "rarity": 2, "price": 500, "stack_limit": 100, "effects": {"heal_amount": 0, "heal_stat": "hp", "return": True, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "지정한 귀환장소로 즉시 이동한다."},
    {"id": 3001, "code": "CONS_TOWN_SCROLL", "name": "마을귀환서", "item_type": "consumable", "sub_type": "소모품", "rarity": 1, "price": 300, "stack_limit": 100, "effects": {"heal_amount": 0, "heal_stat": "hp", "return": False, "town_return": True, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "가장 가까운 안전지역으로 이동한다."},
    {"id": 3002, "code": "CONS_ADV_RETURN", "name": "고급귀환서", "item_type": "consumable", "sub_type": "소모품", "rarity": 3, "price": 1000, "stack_limit": 100, "effects": {"heal_amount": 0, "heal_stat": "hp", "return": False, "town_return": False, "select_return": True, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "원하는 지역의 여관을 선택하여 이동한다."},
    {"id": 3003, "code": "CONS_HP_POT_S", "name": "소HP회복약", "item_type": "consumable", "sub_type": "소모품", "rarity": 1, "price": 50, "stack_limit": 100, "effects": {"heal_amount": 50, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "HP를 50 회복한다."},
    {"id": 3004, "code": "CONS_HP_POT_M", "name": "중HP회복약", "item_type": "consumable", "sub_type": "소모품", "rarity": 1, "price": 100, "stack_limit": 100, "effects": {"heal_amount": 100, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "HP를 100 회복한다."},
    {"id": 3005, "code": "CONS_HP_POT_L", "name": "대HP회복약", "item_type": "consumable", "sub_type": "소모품", "rarity": 2, "price": 200, "stack_limit": 100, "effects": {"heal_amount": 200, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "HP를 200 회복한다."},
    {"id": 3006, "code": "CONS_HP_POT_EL", "name": "특대HP회복약", "item_type": "consumable", "sub_type": "소모품", "rarity": 3, "price": 500, "stack_limit": 100, "effects": {"heal_amount": 500, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "HP를 500 회복한다."},
    {"id": 3007, "code": "CONS_HP_POT_XL", "name": "초HP회복약", "item_type": "consumable", "sub_type": "소모품", "rarity": 4, "price": 1000, "stack_limit": 100, "effects": {"heal_amount": 1000, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "HP를 1000 회복한다."},
    {"id": 3008, "code": "CONS_MP_POT_L", "name": "대MP회복약", "item_type": "consumable", "sub_type": "소모품", "rarity": 2, "price": 200, "stack_limit": 100, "effects": {"heal_amount": 150, "heal_stat": "mp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "MP를 150 회복한다."},
    {"id": 3009, "code": "CONS_MP_POT_EL", "name": "특대MP회복약", "item_type": "consumable", "sub_type": "소모품", "rarity": 3, "price": 500, "stack_limit": 100, "effects": {"heal_amount": 400, "heal_stat": "mp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "MP를 400 회복한다."},
    {"id": 3010, "code": "CONS_HPMP_POT", "name": "HPMP회복약", "item_type": "consumable", "sub_type": "소모품", "rarity": 3, "price": 800, "stack_limit": 100, "effects": {"heal_amount": 300, "heal_stat": "both", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "HP/MP를 300씩 회복한다."},
    {"id": 3011, "code": "CONS_ATK_BUFF", "name": "공격력강화부적", "item_type": "consumable", "sub_type": "소모품", "rarity": 2, "price": 300, "stack_limit": 100, "effects": {"heal_amount": 0, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "attack", "buff_value": 30, "buff_duration": 600, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "10분간 공격력 +30"},
    {"id": 3012, "code": "CONS_DEF_BUFF", "name": "방어력강화부적", "item_type": "consumable", "sub_type": "소모품", "rarity": 2, "price": 300, "stack_limit": 100, "effects": {"heal_amount": 0, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "defense", "buff_value": 20, "buff_duration": 600, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "10분간 방어력 +20"},
    {"id": 3013, "code": "CONS_SPD_BUFF", "name": "신속의두루마리", "item_type": "consumable", "sub_type": "소모품", "rarity": 2, "price": 400, "stack_limit": 100, "effects": {"heal_amount": 0, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "speed", "buff_value": 15, "buff_duration": 600, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "10분간 속도 +15"},
    {"id": 3014, "code": "CONS_FULL_HEAL", "name": "완전회복의비약", "item_type": "consumable", "sub_type": "소모품", "rarity": 4, "price": 2000, "stack_limit": 100, "effects": {"heal_amount": 99999, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "HP/MP를 완전히 회복한다."},
    {"id": 3015, "code": "CONS_REVIVE", "name": "부활의영약", "item_type": "consumable", "sub_type": "소모품", "rarity": 5, "price": 3000, "stack_limit": 100, "effects": {"heal_amount": 0, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": True, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "사망 시 자동 부활 (HP 50%)"},
    {"id": 3016, "code": "CONS_ANTIDOTE", "name": "해독제", "item_type": "consumable", "sub_type": "소모품", "rarity": 1, "price": 150, "stack_limit": 100, "effects": {"heal_amount": 0, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": True, "perm_buff": "", "perm_value": 0}, "description": "모든 독 상태를 해제한다."},
    {"id": 3017, "code": "CONS_BANDAGE", "name": "붕대", "item_type": "consumable", "sub_type": "소모품", "rarity": 1, "price": 50, "stack_limit": 100, "effects": {"heal_amount": 50, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "", "perm_value": 0}, "description": "HP를 50 회복한다."},
    {"id": 3018, "code": "CONS_STRENGTH_ELIXIR", "name": "괴력의비약", "item_type": "consumable", "sub_type": "소모품", "rarity": 5, "price": 5000, "stack_limit": 100, "effects": {"heal_amount": 0, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "attack", "perm_value": 5}, "description": "영구적으로 공격력 +5"},
    {"id": 3019, "code": "CONS_VITALITY_ELIXIR", "name": "생명의비약", "item_type": "consumable", "sub_type": "소모품", "rarity": 5, "price": 5000, "stack_limit": 100, "effects": {"heal_amount": 0, "heal_stat": "hp", "return": False, "town_return": False, "select_return": False, "buff_type": "", "buff_value": 0, "buff_duration": 0, "revive": False, "cure_poison": False, "perm_buff": "max_hp", "perm_value": 50}, "description": "영구적으로 최대HP +50"}
    ]

    for c in consumables:
        db.add(Item(**c))
    db.commit()
    print(f"v6 consumables seeded: {len(consumables)} items")

if __name__ == "__main__":
    seed()
