"""
낙화검심 MEGA 확장 - NPC 50명 추가 (총 70명+)
연애대상 3명 추가 (유하영, 홍소월, 백리연) + 스승/상인/정보상/황성/문파 NPC
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from app.core.database import SessionLocal, engine, Base
from app.models import NPC

def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    if db.query(NPC).filter(NPC.id == 21).count() > 0:
        print("Mega NPCs already seeded!"); db.close(); return

    npcs = [
        # 연애 대상 추가
        NPC(id=21, name="유하영", title="비밀무희", faction="정파→사파",
            dialogue="[유하영] 난 정파의 딸로 태어났어요. 하지만 정파가 나를 버렸어요. 이제는 내가 나를 버릴 차례. 당신... 나를 구원할 수 있나요? 아니면 나와 함께 떨어질 건가요?",
            description="한때 정파의 영웅이었으나 음모에 휘말려 사파로 전락한 비련의 여인.", is_hostile=False, occupation="무희",
            dialogue_options=[{"question":"네 이야기를 들려줘","action":"유하영이 슬픈 눈빛으로 바라본다."}]),
        NPC(id=22, name="홍소월", title="마교교주", faction="마도",
            dialogue="[홍소월] 마도는 악이 아니야. 그저 정파와 다른 길일 뿐. 나와 함께라면 천하를 가질 수 있어. 하지만... 조건이 있어. 네 모든 것을 내게 바쳐.",
            description="흑련교의 젊은 교주. 냉혈한의 가면 아래 순수한 영혼이 숨어 있다.", is_hostile=False, occupation="마교교주",
            dialogue_options=[{"question":"마도에 대해 알려줘","action":"홍소월이 차갑게 웃는다."}]),
        NPC(id=23, name="백리연", title="검선", faction="정파",
            dialogue="[백리연] 검은 나의 전부였소. 그런데... 당신의 검을 보고 생각이 바뀌었소. 어쩌면 검보다 중요한 것이 있는지도 모르겠군.",
            description="무당산의 전설적 여검선. 평생 검에 바친 그녀가 첫 감정을 느낀다.", is_hostile=False, occupation="검객",
            dialogue_options=[{"question":"검술을 가르쳐줘","action":"백리연이 검을 뽑아 든다."}]),
        # 스승/고수
        NPC(id=24, name="무당진인", title="무당산 장문인", faction="정파",
            dialogue="[무당진인] 도는 멀리 있지 않소. 자신의 마음속에 있지. 검을 휘두르지 않고도 이길 수 있을 때 진정한 검선이라 부를 수 있소.",
            description="백발의 도사. 평생 무당산에서 수련한 전설적 고수.", is_hostile=False, occupation="도사/스승",
            ambient_lines=["도를 아느냐, 혹은 도를 따르느냐..."]),
        NPC(id=25, name="소림방장", title="소림사 주지", faction="정파",
            dialogue="[방장] 나무아미타불. 자네의 손에 묻은 피는 이미 많구나. 하지만 아직 돌아올 길은 있네.",
            description="소림사 주지 스님. 무공과 불법 모두 최고 경지의 고승.", is_hostile=False, occupation="승려/스승",
            ambient_lines=["나무아미타불, 무상무념이로다..."]),
        NPC(id=26, name="혈마노괴", title="사파 은둔고수", faction="사파",
            dialogue="[혈마노괴] 흐흐, 제자가 되고 싶다고? 좋아. 하지만 첫 시험은 네 스스로를 죽이는 거다. 진짜냐고? 은유다. 하지만 진짜일 수도 있다.",
            description="사파의 전설적 고수. 예측불가 성격. 제자 되면 최강이거나 미쳐버리거나.", is_hostile=False, occupation="은둔고수", ambient_lines=["흐흐흐... 젊은 피 냄새가 나는군."], quest_giver=True),
        NPC(id=27, name="비연각주", title="자객 길드 마스터", faction="중립",
            dialogue="[비연각주] 암살은 예술이지. 죽음에도 미학이 있어야 해. 자네에게 그 재능이 있는지... 시험해볼까?",
            description="전설의 암살자 길드 '비연각' 수장.", is_hostile=False, occupation="암살길드수장", ambient_lines=["암살은 예술, 기억하라."], quest_giver=True),
        # 상인
        NPC(id=28, name="금전방주", title="금융조직 수장", faction="중립",
            dialogue="[방주] 은전이 곧 힘이오. 강호의 어떤 고수도 내 앞에서는 빚쟁이일 뿐. 이자는... 흐흐.",
            description="강호 금융을 쥔 금전방의 주인. 빌리면 갚지 못한다.", is_hostile=False, occupation="상인", shop_id=8),
        NPC(id=29, name="보물상인", title="희귀 아이템 수집가", faction="중립",
            dialogue="[보물상인] 북해 인어 눈물 진주요, 서역 용뼈 비수. 흥정하기 나름이오.",
            description="희귀템만 취급하는 수집가 겸 상인.", is_hostile=False, occupation="상인/수집가", shop_id=13),
        NPC(id=30, name="강호약사", title="유랑약사", faction="중립",
            dialogue="[약사] 몸의 병은 고쳐도 마음의 병은 약으로 못 고쳐. 하지만 이 '망혼산'이라면... 먹어볼 텐가?",
            description="어떤 병이든 고치는 신비한 약사. 약에는 항상 대가가 있다.", is_hostile=False, occupation="약사/상인", shop_id=5),
        # 정보상/중개인
        NPC(id=31, name="어둠의 정보상", title="지하 정보 네트워크", faction="중립",
            dialogue="[정보상] 강호의 모든 비밀이 내게 흘러들어오지. 그 정보를 감당할 자신이 있나?",
            description="어둠의 정보 네트워크 수장. 진실은 대가를 요구한다.", is_hostile=False, occupation="정보상"),
        NPC(id=32, name="소림고승", title="소림사 달마원", faction="정파",
            dialogue="[고승] 마음이 흔들리면 검도 흔들리네. 명상으로 마음을 가라앉히게. 이것이 진정한 무공 수련의 시작일세.",
            description="소림사 깨달은 고승. 가르침은 단순하지만 깊다.", is_hostile=False, occupation="승려"),
        NPC(id=33, name="수상한 떠돌이", title="정체불명", faction="미상",
            dialogue="[떠돌이] 귀화천... 그 이름을 알고 있나? 모른다면 됐고, 안다면 내게 오게. 할 얘기가 많아.",
            description="귀화천에 대해 아는 듯한 수상한 떠돌이.", is_hostile=False, occupation="정체불명"),
        # 적대 NPC
        NPC(id=34, name="혈랑곡주", title="사파 문파주", faction="사파",
            dialogue="[혈랑곡주] 내 혈랑곡에 온 것을 환영한다! ...네 목숨을 바쳐서.",
            description="인간의 피를 마시며 수련하는 흡혈 마인.", is_hostile=True, occupation="사파문파주"),
        NPC(id=35, name="흑풍채주", title="산채 두목", faction="사파",
            dialogue="[채주] 목숨을 부지하려면 네 가진 것 전부를 내놔라! 목숨까지 포함해서!",
            description="흑풍채의 악명 높은 산채주.", is_hostile=True, occupation="산채두목"),
        NPC(id=36, name="마황숭배자", title="광신도", faction="마도",
            dialogue="[숭배자] 마황이여! 이 세속의 벌레를 당신께 바칩니다! 더 많은 피를!",
            description="마황을 숭배하는 광신도. 제물을 찾아 배회한다.", is_hostile=True, occupation="광신도"),
        # 마을 NPC
        NPC(id=37, name="주막 주모", title="객잔거리 요리사", faction="중립",
            dialogue="[주모] 어서 오시게! 오늘의 특별 메뉴는 만독림 버섯탕! ...해독제도 따로 판다네.",
            description="객잔거리 주막의 활기찬 주모.", is_hostile=False, occupation="요리사", shop_id=10),
        NPC(id=38, name="떠돌이 악사", title="거리 음악가", faction="중립",
            dialogue="[악사] 한 곡조 들으시겠소? 이 비파는 죽은 연인의 뼈로 만든 거요. 그녀의 혼이 현을 흐른답니다.",
            description="기이한 악사. 그의 음악은 잊힌 기억을 깨운다.", is_hostile=False, occupation="음악가"),
        NPC(id=39, name="길거리 천기사", title="점술가", faction="중립",
            dialogue="[천기사] 자네의 운명선은... 두 개로 갈라져 있군. 한쪽은 영광, 다른 쪽은 파멸.",
            description="점을 치는 천기사. 예언은 놀랍도록 정확하다.", is_hostile=False, occupation="점술가"),
        NPC(id=40, name="술 취한 검객", title="정체불명 협객", faction="중립",
            dialogue="[검객] *꼴깍* 내 검술이 궁금한가? 술값만 내면 가르쳐주지. 쓰러지기 전에...",
            description="술에 절은 검객. 취하면 우스꽝스럽지만 검은 전설적.", is_hostile=False, occupation="협객"),
        # 황성 NPC
        NPC(id=41, name="황실근위대장", title="황궁 수호자", faction="특수",
            dialogue="[대장] 황제 폐하의 명령 없인 누구도 이 문을 통과할 수 없다.",
            description="황실 근위대 대장. 어떤 상황에도 무표정.", is_hostile=False, occupation="군인"),
        NPC(id=42, name="내시총관", title="황실 내무부", faction="특수",
            dialogue="[총관] 황실과 강호는 다른 세상. 하지만 때때로 만나기도 하지요.",
            description="황실의 실세. 겉으론 공손하나 속은 미궁.", is_hostile=False, occupation="황실관리", shop_id=12, ambient_lines=["황실과 강호, 때로는 같은 하늘 아래 있지요."], quest_giver=True),
        NPC(id=43, name="공주 화타", title="황실 공주", faction="특수",
            dialogue="[공주] 강호를 동경해온 지 오래입니다! 제발 절 데리고 이 새장에서 나가주세요!",
            description="모험을 꿈꾸는 공주. 구출 시 추격대가 따라붙는다.", is_hostile=False, occupation="황족"),
        # 문파 NPC
        NPC(id=44, name="청람수석제자", title="차기 문주 후보", faction="정파",
            dialogue="[수석제자] 청람검문의 검술은 단순함에 깊이가 있소. 1년만 수련하면 반드시 한 단계 올라설 것이오.",
            description="청람검문 수석제자. 성실하고 겸손한 성품.", is_hostile=False, occupation="무인/제자"),
        NPC(id=45, name="운소궁주", title="운소궁 지배자", faction="정파",
            dialogue="[궁주] 여성이 강호에서 살아남으려면 검 이상으로 지혜가 필요하오. 내 궁에 입문한다면 가르쳐주지.",
            description="운소궁의 궁주. 지혜와 미모를 겸비한 여성 무인.", is_hostile=False, occupation="문파주"),
        NPC(id=46, name="서원학사", title="백운서원 석학", faction="정파",
            dialogue="[학사] 무공은 살상술이 아니네. 이치를 깨달은 자만이 진정한 고수라 할 수 있지.",
            description="백운서원 노학자. 진법의 대가.", is_hostile=False, occupation="학자"),
        # 적대 조직 NPC
        NPC(id=47, name="귀화천밀정", title="귀화천 첩자", faction="적대",
            dialogue="검은 밀복의 인물이 당신을 발견하고 재빨리 사라진다. 추격할 것인가?",
            description="귀화천 소속 밀정. 추적 시 비밀 기지로 이어짐.", is_hostile=True, occupation="밀정/첩자"),
        NPC(id=48, name="흑련교호법", title="흑련교 간부", faction="마도",
            dialogue="[호법] 흑련교에 발을 들이다니 용감하군. 목숨이 아깝지 않소?",
            description="흑련교 호법장로. 강력한 내공의 소유자.", is_hostile=True, occupation="마도간부"),
        NPC(id=49, name="야명곡주", title="야명곡 수령", faction="사파",
            dialogue="[곡주] 어둠 속에선 모든 것이 평등하지. 정파든 사파든 모두 똑같이... 죽는다.",
            description="야명곡의 음산한 수령. 어둠 속 암습을 즐긴다.", is_hostile=True, occupation="사파수령"),
        # 기타
        NPC(id=50, name="도굴꾼", title="고분 탐험가", faction="중립",
            dialogue="[도굴꾼] 지하에 아주 오래된 무덤이 있소. 전설의 비급이 잠들어 있다던데... 같이 파볼 생각 없소?",
            description="고분 탐험 전문가. 숨겨진 던전과 퀘스트로 이끈다.", is_hostile=False, occupation="탐험가"),
        NPC(id=51, name="탈옥수", title="도주 중인 죄수", faction="미상",
            dialogue="[탈옥수] 넌 나를 잡을 수 없어. 난 이미... 죽어야 마땅한 놈이니까.",
            description="지하 감옥 탈출자. 그에겐 강호를 뒤흔들 비밀이 있다.", is_hostile=False, occupation="도주죄수"),
        NPC(id=52, name="신비한 노파", title="예언자", faction="미상",
            dialogue="[노파] 선택의 기로에 설 것이다. 검을 버리면 사랑, 검을 잡으면 천하. 무엇을 택하겠니?",
            description="나타났다 사라지는 신비한 노파. 말은 항상 예언이 된다.", is_hostile=False, occupation="예언자", ambient_lines=["선택의 기로에 서게 될 거야...", "운명은 이미 정해져 있단다."], quest_giver=True),
        NPC(id=53, name="무명무사", title="이름 없는 절세고수", faction="미상",
            dialogue="망토를 깊게 눌러쓴 무사. 그의 눈빛만으로도 압도당한다. 가장 위험한 인물임은 분명하다.",
            description="정체불명의 절세고수. 충고 한마디에 무공이 상승.", is_hostile=False, occupation="절세고수", ambient_lines=["*말없이 당신을 응시한다*"], quest_giver=True),
        NPC(id=54, name="백련교주", title="백련교 수장", faction="사파",
            dialogue="[백련교주] 순수한 마음이 가장 강한 무기요. 하지만 내 마음은 이미 물들었소.",
            description="이상과 현실 사이에서 번뇌하는 비극적 지도자.", is_hostile=True, occupation="사파교주"),
        NPC(id=55, name="봉황사자", title="봉황단애 은둔자", faction="정파",
            dialogue="[사자] 봉황의 축복을 받으려면 먼저 네 마음을 증명해라.",
            description="봉황단애에 은둔한 무인. 특별한 기연을 준다.", is_hostile=False, occupation="은둔자", ambient_lines=["봉황의 축복이 네게 함께하기를..."], quest_giver=True),
        NPC(id=56, name="설인족장", title="설봉 부족장", faction="중립",
            dialogue="[족장] 외부인은 처음이군. 떠나시오. 아니면... 눈 속에 묻히든가.",
            description="천산설봉 은둔 부족의 족장. 예의에 따라 도움을 준다.", is_hostile=True, occupation="부족장", ambient_lines=["외부인... 조심하는 게 좋을 거요."], quest_giver=True),
        # 추가 NPC 14명
        NPC(id=57, name="협객풍운", title="정파 방랑검객", faction="정파",
            dialogue="[풍운] 의리를 위해 검을 뽑았소. 나와 함께 싸우시겠소?",
            description="정파의 방랑검객. 약자를 위한 검을 휘두른다.", is_hostile=False, occupation="방랑검객"),
        NPC(id=58, name="살수은영", title="암살자", faction="중립",
            dialogue="[은영] 의뢰비 500은전. 표적은 3일 내 제거한다.",
            description="프리랜서 암살자. 돈만 내면 누구든 처치한다.", is_hostile=False, occupation="암살자"),
        NPC(id=59, name="고서수집가", title="희귀서적 전문", faction="중립",
            dialogue="[수집가] 비급조각과 교환하시겠소? 내게는 희귀한 내공심법이 있소.",
            description="고서적을 수집하는 학자형 상인.", is_hostile=False, occupation="상인/학자"),
        NPC(id=60, name="술집기녀", title="청루 예인", faction="중립",
            dialogue="[기녀] 한 곡조 들으시겠소? 소문에 의하면... 귀화천의 밀사가 이 마을에 왔답니다.",
            description="청루의 기녀. 노래 속에 강호의 정보를 숨긴다.", is_hostile=False, occupation="예인"),
        NPC(id=61, name="산적회계", title="산채 회계사", faction="사파",
            dialogue="[회계] 오늘 수입은 은전 30닢. 산적질도 장사가 안 되는군.",
            description="산채에서 회계를 보는 희귀한 NPC. 재밌는 정보를 준다.", is_hostile=False, occupation="회계사"),
        NPC(id=62, name="마을촌장", title="입문마을 촌장", faction="정파",
            dialogue="[촌장] 마을에 오신 걸 환영하오. 편히 쉬었다 가시게.",
            description="입문마을의 촌장. 마을 퀘스트를 준다.", is_hostile=False, occupation="촌장",
            ambient_lines=["오늘도 강호는 평화롭군...", "젊은이, 잠시 쉬었다 가게나."], quest_giver=True),
        NPC(id=63, name="의원", title="마을 의원", faction="중립",
            dialogue="[의원] 상처를 보여주시게. 치료비는 은전 10닢.",
            description="마을의 의원. 저렴하게 체력을 회복시켜준다.", is_hostile=False, occupation="의원",
            ambient_lines=["어디 다친 곳은 없나?", "약은 미리 준비해두는 게 좋아.", "내가 만든 환약은 특별하지."]),
        NPC(id=64, name="떠돌이장사꾼", title="행상인", faction="중립",
            dialogue="[장사꾼] 싸다 싸! 오늘만 특별 할인!",
            description="떠돌이 장사꾼. 가끔 희귀템을 판다.", is_hostile=False, occupation="행상인"),
        NPC(id=65, name="무림기자", title="무림소식통", faction="중립",
            dialogue="[기자] 강호 신문! 오늘의 톱뉴스는 청람검문 신입제자 모집!",
            description="강호의 소식을 전하는 NPC.", is_hostile=False, occupation="기자"),
        NPC(id=66, name="수상한노인", title="기연의 전달자", faction="미상",
            dialogue="[노인] 자네에게 기연이 있음을 느꼈네. 이걸 받게나.",
            description="기연을 전달하는 신비로운 노인.", is_hostile=False, occupation="기연전달자"),
        NPC(id=67, name="흑도두목", title="흑도 조직 두목", faction="사파",
            dialogue="[두목] 이 구역은 우리 흑도가 접수했다. 목숨이 아까우면 꺼져라.",
            description="흑도 조직의 두목.", is_hostile=True, occupation="조직두목"),
        NPC(id=68, name="협객연화", title="여성 무인", faction="정파",
            dialogue="[연화] 검을 배우고 싶나요? 기초는 제가 가르쳐드릴 수 있어요.",
            description="초보자에게 검술을 가르쳐주는 여협.", is_hostile=False, occupation="여성무인"),
        NPC(id=69, name="신묘한도사", title="도교은둔자", faction="정파",
            dialogue="[도사] 도를 닦으면 모든 것이 선명해진다. 잠시 앉아 명상해보시게.",
            description="도교의 은둔자. 명상으로 경험치를 주는 NPC.", is_hostile=False, occupation="도사"),
        NPC(id=70, name="밀수업자", title="밀수조직 총책", faction="중립",
            dialogue="[밀수업자] 합법적인 거래는 관두고... 진짜 필요한 걸 원한다면 나를 찾아.",
            description="밀수 네트워크의 총책. 암시장보다 깊은 물건을 취급.", is_hostile=False, occupation="밀수총책"),
    ]

    for n in npcs:
        db.add(n)
    db.commit(); db.close()
    print(f"Seeded {len(npcs)} NPCs! (Total: 70+)")

if __name__ == "__main__":
    seed()
