"""
낙화검심 MEGA 확장 - 아이템 250종 추가 (총 350종+)
강화재료 5종 포함 (강화석/보호석/고급강화석/축복의서/수호부적)
"""
import sys, os, json
sys.path.insert(0, os.path.dirname(__file__))
from app.core.database import SessionLocal, engine, Base
from app.models import Item

def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    if db.query(Item).filter(Item.id == 101).count() > 0:
        print("Mega items already seeded!"); db.close(); return
    items = [
  {
    "id": 101,
    "name": "강화석",
    "item_type": "consumable",
    "sub_type": "재료",
    "price": 50,
    "rarity": 1,
    "stats": "{\"heal_amount\": 0}",
    "effects": "\"\\uc544\\uc774\\ud15c \\uac15\\ud654\\uc5d0 \\uc0ac\\uc6a9\\ub418\\ub294 \\uae30\\ubcf8 \\uc7ac\\ub8cc.\"",
    "description": "아이템 강화에 사용되는 기본 재료."
  },
  {
    "id": 102,
    "name": "보호석",
    "item_type": "consumable",
    "sub_type": "재료",
    "price": 200,
    "rarity": 2,
    "stats": "{\"heal_amount\": 0}",
    "effects": "\"\\uac15\\ud654 \\uc2e4\\ud328 \\uc2dc \\uc544\\uc774\\ud15c \\ub808\\ubca8\\uc744 \\ubcf4\\ud638.\"",
    "description": "강화 실패 시 아이템 레벨을 보호."
  },
  {
    "id": 103,
    "name": "고급강화석",
    "item_type": "consumable",
    "sub_type": "재료",
    "price": 500,
    "rarity": 3,
    "stats": "{\"heal_amount\": 0}",
    "effects": "\"\\uac15\\ud654 \\uc131\\uacf5\\ub960\\uc744 20% \\uc0c1\\uc2b9.\"",
    "description": "강화 성공률을 20% 상승."
  },
  {
    "id": 104,
    "name": "축복의서",
    "item_type": "consumable",
    "sub_type": "재료",
    "price": 1000,
    "rarity": 4,
    "stats": "{\"heal_amount\": 0}",
    "effects": "\"\\uac15\\ud654 \\uc131\\uacf5 \\uc2dc 2\\ub2e8\\uacc4 \\uc0c1\\uc2b9 \\ud655\\ub960 \\ubd80\\uc5ec.\"",
    "description": "강화 성공 시 2단계 상승 확률 부여."
  },
  {
    "id": 105,
    "name": "수호부적",
    "item_type": "consumable",
    "sub_type": "재료",
    "price": 800,
    "rarity": 3,
    "stats": "{\"heal_amount\": 0}",
    "effects": "\"\\uac15\\ud654 \\uc2e4\\ud328 \\ud69f\\uc218 \\ucd08\\uae30\\ud654.\"",
    "description": "강화 실패 횟수 초기화."
  },
  {
    "id": 106,
    "name": "혈월검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 360,
    "rarity": 3,
    "stats": "{\"attack\": 27}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 3\"",
    "description": "희귀 무기. 등급 3"
  },
  {
    "id": 107,
    "name": "백학검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 360,
    "rarity": 3,
    "stats": "{\"attack\": 27}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 3\"",
    "description": "희귀 무기. 등급 3"
  },
  {
    "id": 108,
    "name": "흑룡도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 360,
    "rarity": 3,
    "stats": "{\"attack\": 27}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 3\"",
    "description": "희귀 무기. 등급 3"
  },
  {
    "id": 109,
    "name": "봉황도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 360,
    "rarity": 3,
    "stats": "{\"attack\": 27}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 3\"",
    "description": "희귀 무기. 등급 3"
  },
  {
    "id": 110,
    "name": "파천대검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 360,
    "rarity": 3,
    "stats": "{\"attack\": 27}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 3\"",
    "description": "희귀 무기. 등급 3"
  },
  {
    "id": 111,
    "name": "비연검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 360,
    "rarity": 3,
    "stats": "{\"attack\": 27}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 3\"",
    "description": "희귀 무기. 등급 3"
  },
  {
    "id": 112,
    "name": "칠성보도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 360,
    "rarity": 3,
    "stats": "{\"attack\": 27}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 3\"",
    "description": "희귀 무기. 등급 3"
  },
  {
    "id": 113,
    "name": "청운검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 360,
    "rarity": 3,
    "stats": "{\"attack\": 27}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 3\"",
    "description": "희귀 무기. 등급 3"
  },
  {
    "id": 114,
    "name": "만월도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 360,
    "rarity": 3,
    "stats": "{\"attack\": 27}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 3\"",
    "description": "희귀 무기. 등급 3"
  },
  {
    "id": 115,
    "name": "벽호검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 480,
    "rarity": 4,
    "stats": "{\"attack\": 32}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 4\"",
    "description": "희귀 무기. 등급 4"
  },
  {
    "id": 116,
    "name": "금사검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 480,
    "rarity": 4,
    "stats": "{\"attack\": 32}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 4\"",
    "description": "희귀 무기. 등급 4"
  },
  {
    "id": 117,
    "name": "옥룡도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 480,
    "rarity": 4,
    "stats": "{\"attack\": 32}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 4\"",
    "description": "희귀 무기. 등급 4"
  },
  {
    "id": 118,
    "name": "뇌전검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 480,
    "rarity": 4,
    "stats": "{\"attack\": 32}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 4\"",
    "description": "희귀 무기. 등급 4"
  },
  {
    "id": 119,
    "name": "한빙도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 480,
    "rarity": 4,
    "stats": "{\"attack\": 32}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 4\"",
    "description": "희귀 무기. 등급 4"
  },
  {
    "id": 120,
    "name": "폭염검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 480,
    "rarity": 4,
    "stats": "{\"attack\": 32}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 4\"",
    "description": "희귀 무기. 등급 4"
  },
  {
    "id": 121,
    "name": "은린검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 480,
    "rarity": 4,
    "stats": "{\"attack\": 32}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 4\"",
    "description": "희귀 무기. 등급 4"
  },
  {
    "id": 122,
    "name": "자하도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 480,
    "rarity": 4,
    "stats": "{\"attack\": 32}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 4\"",
    "description": "희귀 무기. 등급 4"
  },
  {
    "id": 123,
    "name": "태극검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 480,
    "rarity": 4,
    "stats": "{\"attack\": 32}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 4\"",
    "description": "희귀 무기. 등급 4"
  },
  {
    "id": 124,
    "name": "수라도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 480,
    "rarity": 4,
    "stats": "{\"attack\": 32}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 4\"",
    "description": "희귀 무기. 등급 4"
  },
  {
    "id": 125,
    "name": "백련검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 126,
    "name": "철혈도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 127,
    "name": "쌍월검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 128,
    "name": "대붕검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 129,
    "name": "와룡도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 130,
    "name": "광풍검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 131,
    "name": "절영도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 132,
    "name": "만파검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 133,
    "name": "역천도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 134,
    "name": "비검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 135,
    "name": "파사검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 136,
    "name": "영웅검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 137,
    "name": "마왕도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 138,
    "name": "신검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 139,
    "name": "용린검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 140,
    "name": "봉신도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 141,
    "name": "제왕검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 142,
    "name": "암살검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 143,
    "name": "투혼도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 144,
    "name": "혈전검",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 145,
    "name": "패왕도",
    "item_type": "weapon",
    "sub_type": "검",
    "price": 600,
    "rarity": 5,
    "stats": "{\"attack\": 37}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uae30. \\ub4f1\\uae09 5\"",
    "description": "희귀 무기. 등급 5"
  },
  {
    "id": 146,
    "name": "금사도포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 300,
    "rarity": 3,
    "stats": "{\"defense\": 20, \"hp\": 60}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 3\"",
    "description": "고급 방어구. 등급 3"
  },
  {
    "id": 147,
    "name": "흑룡갑",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 300,
    "rarity": 3,
    "stats": "{\"defense\": 20, \"hp\": 60}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 3\"",
    "description": "고급 방어구. 등급 3"
  },
  {
    "id": 148,
    "name": "백학포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 300,
    "rarity": 3,
    "stats": "{\"defense\": 20, \"hp\": 60}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 3\"",
    "description": "고급 방어구. 등급 3"
  },
  {
    "id": 149,
    "name": "봉황의",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 300,
    "rarity": 3,
    "stats": "{\"defense\": 20, \"hp\": 60}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 3\"",
    "description": "고급 방어구. 등급 3"
  },
  {
    "id": 150,
    "name": "칠성연갑",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 300,
    "rarity": 3,
    "stats": "{\"defense\": 20, \"hp\": 60}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 3\"",
    "description": "고급 방어구. 등급 3"
  },
  {
    "id": 151,
    "name": "벽호도포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 300,
    "rarity": 3,
    "stats": "{\"defense\": 20, \"hp\": 60}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 3\"",
    "description": "고급 방어구. 등급 3"
  },
  {
    "id": 152,
    "name": "청운갑",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 300,
    "rarity": 3,
    "stats": "{\"defense\": 20, \"hp\": 60}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 3\"",
    "description": "고급 방어구. 등급 3"
  },
  {
    "id": 153,
    "name": "만월포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 300,
    "rarity": 3,
    "stats": "{\"defense\": 20, \"hp\": 60}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 3\"",
    "description": "고급 방어구. 등급 3"
  },
  {
    "id": 154,
    "name": "금강연갑",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 300,
    "rarity": 3,
    "stats": "{\"defense\": 20, \"hp\": 60}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 3\"",
    "description": "고급 방어구. 등급 3"
  },
  {
    "id": 155,
    "name": "자하도포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 400,
    "rarity": 4,
    "stats": "{\"defense\": 24, \"hp\": 80}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 4\"",
    "description": "고급 방어구. 등급 4"
  },
  {
    "id": 156,
    "name": "태극포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 400,
    "rarity": 4,
    "stats": "{\"defense\": 24, \"hp\": 80}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 4\"",
    "description": "고급 방어구. 등급 4"
  },
  {
    "id": 157,
    "name": "수라갑",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 400,
    "rarity": 4,
    "stats": "{\"defense\": 24, \"hp\": 80}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 4\"",
    "description": "고급 방어구. 등급 4"
  },
  {
    "id": 158,
    "name": "백련도포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 400,
    "rarity": 4,
    "stats": "{\"defense\": 24, \"hp\": 80}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 4\"",
    "description": "고급 방어구. 등급 4"
  },
  {
    "id": 159,
    "name": "철혈갑",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 400,
    "rarity": 4,
    "stats": "{\"defense\": 24, \"hp\": 80}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 4\"",
    "description": "고급 방어구. 등급 4"
  },
  {
    "id": 160,
    "name": "쌍월포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 400,
    "rarity": 4,
    "stats": "{\"defense\": 24, \"hp\": 80}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 4\"",
    "description": "고급 방어구. 등급 4"
  },
  {
    "id": 161,
    "name": "대붕갑",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 400,
    "rarity": 4,
    "stats": "{\"defense\": 24, \"hp\": 80}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 4\"",
    "description": "고급 방어구. 등급 4"
  },
  {
    "id": 162,
    "name": "와룡포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 400,
    "rarity": 4,
    "stats": "{\"defense\": 24, \"hp\": 80}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 4\"",
    "description": "고급 방어구. 등급 4"
  },
  {
    "id": 163,
    "name": "광풍갑",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 400,
    "rarity": 4,
    "stats": "{\"defense\": 24, \"hp\": 80}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 4\"",
    "description": "고급 방어구. 등급 4"
  },
  {
    "id": 164,
    "name": "절영도포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 400,
    "rarity": 4,
    "stats": "{\"defense\": 24, \"hp\": 80}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 4\"",
    "description": "고급 방어구. 등급 4"
  },
  {
    "id": 165,
    "name": "만파갑",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 500,
    "rarity": 5,
    "stats": "{\"defense\": 28, \"hp\": 100}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 5\"",
    "description": "고급 방어구. 등급 5"
  },
  {
    "id": 166,
    "name": "영웅갑주",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 500,
    "rarity": 5,
    "stats": "{\"defense\": 28, \"hp\": 100}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 5\"",
    "description": "고급 방어구. 등급 5"
  },
  {
    "id": 167,
    "name": "마왕포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 500,
    "rarity": 5,
    "stats": "{\"defense\": 28, \"hp\": 100}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 5\"",
    "description": "고급 방어구. 등급 5"
  },
  {
    "id": 168,
    "name": "용린갑",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 500,
    "rarity": 5,
    "stats": "{\"defense\": 28, \"hp\": 100}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 5\"",
    "description": "고급 방어구. 등급 5"
  },
  {
    "id": 169,
    "name": "봉신도포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 500,
    "rarity": 5,
    "stats": "{\"defense\": 28, \"hp\": 100}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 5\"",
    "description": "고급 방어구. 등급 5"
  },
  {
    "id": 170,
    "name": "제왕갑주",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 500,
    "rarity": 5,
    "stats": "{\"defense\": 28, \"hp\": 100}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 5\"",
    "description": "고급 방어구. 등급 5"
  },
  {
    "id": 171,
    "name": "암살복",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 500,
    "rarity": 5,
    "stats": "{\"defense\": 28, \"hp\": 100}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 5\"",
    "description": "고급 방어구. 등급 5"
  },
  {
    "id": 172,
    "name": "투혼갑",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 500,
    "rarity": 5,
    "stats": "{\"defense\": 28, \"hp\": 100}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 5\"",
    "description": "고급 방어구. 등급 5"
  },
  {
    "id": 173,
    "name": "혈전도포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 500,
    "rarity": 5,
    "stats": "{\"defense\": 28, \"hp\": 100}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 5\"",
    "description": "고급 방어구. 등급 5"
  },
  {
    "id": 174,
    "name": "패왕갑주",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 500,
    "rarity": 5,
    "stats": "{\"defense\": 28, \"hp\": 100}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 5\"",
    "description": "고급 방어구. 등급 5"
  },
  {
    "id": 175,
    "name": "신선도포",
    "item_type": "armor",
    "sub_type": "도포",
    "price": 500,
    "rarity": 5,
    "stats": "{\"defense\": 28, \"hp\": 100}",
    "effects": "\"\\uace0\\uae09 \\ubc29\\uc5b4\\uad6c. \\ub4f1\\uae09 5\"",
    "description": "고급 방어구. 등급 5"
  },
  {
    "id": 176,
    "name": "대환단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 130,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +200 \\ud68c\\ubcf5\"",
    "description": "체력 +200 회복"
  },
  {
    "id": 177,
    "name": "천년설삼",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 130,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +200 \\ud68c\\ubcf5\"",
    "description": "체력 +200 회복"
  },
  {
    "id": 178,
    "name": "만년하수오",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 130,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +200 \\ud68c\\ubcf5\"",
    "description": "체력 +200 회복"
  },
  {
    "id": 179,
    "name": "구전환골단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 130,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +200 \\ud68c\\ubcf5\"",
    "description": "체력 +200 회복"
  },
  {
    "id": 180,
    "name": "태을금단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 130,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +200 \\ud68c\\ubcf5\"",
    "description": "체력 +200 회복"
  },
  {
    "id": 181,
    "name": "자하영약",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 130,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +200 \\ud68c\\ubcf5\"",
    "description": "체력 +200 회복"
  },
  {
    "id": 182,
    "name": "구화옥로환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 130,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +200 \\ud68c\\ubcf5\"",
    "description": "체력 +200 회복"
  },
  {
    "id": 183,
    "name": "벽력단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 130,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +200 \\ud68c\\ubcf5\"",
    "description": "체력 +200 회복"
  },
  {
    "id": 184,
    "name": "백년선단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 130,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +200 \\ud68c\\ubcf5\"",
    "description": "체력 +200 회복"
  },
  {
    "id": 185,
    "name": "소림대환단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 130,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +200 \\ud68c\\ubcf5\"",
    "description": "체력 +200 회복"
  },
  {
    "id": 186,
    "name": "천향옥로",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 130,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +200 \\ud68c\\ubcf5\"",
    "description": "체력 +200 회복"
  },
  {
    "id": 187,
    "name": "오색영약",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 188,
    "name": "혈삼보환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 189,
    "name": "주작단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 190,
    "name": "현무단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 191,
    "name": "청룡단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 192,
    "name": "백호단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 193,
    "name": "기사회춘환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 194,
    "name": "영약왕",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 195,
    "name": "구명금단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 196,
    "name": "통맥대환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 197,
    "name": "증원대단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 198,
    "name": "빙심대환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 160,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +240 \\ud68c\\ubcf5\"",
    "description": "체력 +240 회복"
  },
  {
    "id": 199,
    "name": "소환대단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 200,
    "name": "주사대약",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 201,
    "name": "녹삼대보환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 202,
    "name": "환골대단",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 203,
    "name": "탈태대환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 204,
    "name": "내공대환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 205,
    "name": "칠보대환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 206,
    "name": "옥로대밀",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 207,
    "name": "혈삼왕",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 208,
    "name": "수라환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 209,
    "name": "마왕환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 210,
    "name": "제왕환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 211,
    "name": "패왕환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 212,
    "name": "신선환",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 213,
    "name": "봉황알",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 214,
    "name": "용의비늘",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 215,
    "name": "기린뿔",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 216,
    "name": "현무껍질",
    "item_type": "consumable",
    "sub_type": "영약",
    "price": 190,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\uccb4\\ub825 +280 \\ud68c\\ubcf5\"",
    "description": "체력 +280 회복"
  },
  {
    "id": 217,
    "name": "칠절독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 80,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 218,
    "name": "만독고",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 80,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 219,
    "name": "백화연정독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 80,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 220,
    "name": "빙백독장",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 80,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 221,
    "name": "오독비수",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 80,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 222,
    "name": "망혼산",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 80,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 223,
    "name": "혈마독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 80,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 224,
    "name": "부사독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 80,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 225,
    "name": "천향두단산",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 105,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 226,
    "name": "만사심독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 105,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 227,
    "name": "탈혼독침",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 105,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 228,
    "name": "비엽독침",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 105,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 229,
    "name": "독룡독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 105,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 230,
    "name": "봉미독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 105,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 231,
    "name": "수라독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 105,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 232,
    "name": "흑연독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 105,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 233,
    "name": "적사독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 105,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 234,
    "name": "청마독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 105,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 235,
    "name": "황룡독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 130,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 236,
    "name": "파멸독",
    "item_type": "consumable",
    "sub_type": "독약",
    "price": 130,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\uc801\\uc5d0\\uac8c DOT \\ud53c\\ud574\"",
    "description": "적에게 DOT 피해"
  },
  {
    "id": 237,
    "name": "용의비늘목걸이",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 600,
    "rarity": 3,
    "stats": "{\"hp\": 90, \"mp\": 45}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 238,
    "name": "봉황깃털반지",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 600,
    "rarity": 3,
    "stats": "{\"hp\": 90, \"mp\": 45}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 239,
    "name": "기린뿔팔찌",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 600,
    "rarity": 3,
    "stats": "{\"hp\": 90, \"mp\": 45}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 240,
    "name": "현무돌목걸이",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 600,
    "rarity": 3,
    "stats": "{\"hp\": 90, \"mp\": 45}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 241,
    "name": "백호이빨반지",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 600,
    "rarity": 3,
    "stats": "{\"hp\": 90, \"mp\": 45}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 242,
    "name": "수호부적목걸이",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 600,
    "rarity": 3,
    "stats": "{\"hp\": 90, \"mp\": 45}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 243,
    "name": "혼돈의반지",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 800,
    "rarity": 4,
    "stats": "{\"hp\": 120, \"mp\": 60}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 244,
    "name": "영웅의증표",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 800,
    "rarity": 4,
    "stats": "{\"hp\": 120, \"mp\": 60}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 245,
    "name": "마왕의인장",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 800,
    "rarity": 4,
    "stats": "{\"hp\": 120, \"mp\": 60}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 246,
    "name": "제왕의왕관조각",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 800,
    "rarity": 4,
    "stats": "{\"hp\": 120, \"mp\": 60}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 247,
    "name": "칠성팔찌",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 800,
    "rarity": 4,
    "stats": "{\"hp\": 120, \"mp\": 60}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 248,
    "name": "혈월목걸이",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 800,
    "rarity": 4,
    "stats": "{\"hp\": 120, \"mp\": 60}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 249,
    "name": "빙궁팔찌",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 800,
    "rarity": 4,
    "stats": "{\"hp\": 120, \"mp\": 60}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 250,
    "name": "뇌전반지",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 800,
    "rarity": 4,
    "stats": "{\"hp\": 120, \"mp\": 60}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 251,
    "name": "마황목걸이",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 1000,
    "rarity": 5,
    "stats": "{\"hp\": 150, \"mp\": 75}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 252,
    "name": "용문반지",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 1000,
    "rarity": 5,
    "stats": "{\"hp\": 150, \"mp\": 75}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 253,
    "name": "귀곡부적",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 1000,
    "rarity": 5,
    "stats": "{\"hp\": 150, \"mp\": 75}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 254,
    "name": "봉황팔찌",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 1000,
    "rarity": 5,
    "stats": "{\"hp\": 150, \"mp\": 75}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 255,
    "name": "설봉왕관",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 1000,
    "rarity": 5,
    "stats": "{\"hp\": 150, \"mp\": 75}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 256,
    "name": "사신의인장",
    "item_type": "accessory",
    "sub_type": "장신구",
    "price": 1000,
    "rarity": 5,
    "stats": "{\"hp\": 150, \"mp\": 75}",
    "effects": "\"\\ud2b9\\ubcc4\\ud55c \\ub2a5\\ub825\\uc758 \\uc7a5\\uc2e0\\uad6c\"",
    "description": "특별한 능력의 장신구"
  },
  {
    "id": 257,
    "name": "낙화검결잔장8",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1200,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 258,
    "name": "낙화검결잔장9",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1200,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 259,
    "name": "낙화검결잔장10",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1200,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 260,
    "name": "천잠고보",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1200,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 261,
    "name": "월하검보",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1200,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 262,
    "name": "구음진경잔본2",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1200,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 263,
    "name": "구양신공잔본2",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1200,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 264,
    "name": "태현경잔본2",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1200,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 265,
    "name": "북명신공잔본2",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 266,
    "name": "건곤대나이잔본2",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 267,
    "name": "청람비전2",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 268,
    "name": "혈하문비전",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 269,
    "name": "흑련교밀전",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 270,
    "name": "야명곡비급",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 271,
    "name": "운소궁비전",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 272,
    "name": "백운서원고서",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 273,
    "name": "무당산검경",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 274,
    "name": "소림역근경",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 1600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 275,
    "name": "화산파검보",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 276,
    "name": "개방타구봉법",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 277,
    "name": "비연각살수비급",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 278,
    "name": "마황의서",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 279,
    "name": "용문비전",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 280,
    "name": "귀곡밀서",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 281,
    "name": "봉황단애비급",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 282,
    "name": "설산빙궁비전",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 283,
    "name": "황실무경",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 284,
    "name": "진시황병법",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 285,
    "name": "주작비급",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 286,
    "name": "현무진경",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 287,
    "name": "청룡비전",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 288,
    "name": "백호밀전",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 289,
    "name": "기린고서",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 290,
    "name": "봉황비급",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 291,
    "name": "흑사마경",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 292,
    "name": "뇌신비급",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 293,
    "name": "빙룡비전",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 294,
    "name": "마룡고서",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 295,
    "name": "혈월검보",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 296,
    "name": "천마비급",
    "item_type": "rare",
    "sub_type": "비급",
    "price": 2000,
    "rarity": 5,
    "stats": "{}",
    "effects": "\"\\ud76c\\uadc0 \\ubb34\\uacf5 \\uc2b5\\ub4dd\\uc6a9 \\ube44\\uae09 \\uc870\\uac01/\\uc11c\\uc801\"",
    "description": "희귀 무공 습득용 비급 조각/서적"
  },
  {
    "id": 297,
    "name": "벚꽃잎부적",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 150,
    "rarity": 1,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 298,
    "name": "낙화꽃잎",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 150,
    "rarity": 1,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 299,
    "name": "검은깃털",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 150,
    "rarity": 1,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 300,
    "name": "용의눈물",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 150,
    "rarity": 1,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 301,
    "name": "봉황의재",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 150,
    "rarity": 1,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 302,
    "name": "혈랑의증표",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 150,
    "rarity": 1,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 303,
    "name": "사신의계약서",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 150,
    "rarity": 1,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 304,
    "name": "제왕의인장",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 150,
    "rarity": 1,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 305,
    "name": "패왕의망토",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 150,
    "rarity": 1,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 306,
    "name": "신선의날개",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 150,
    "rarity": 1,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 307,
    "name": "황금나침반",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 308,
    "name": "암시장입장권",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 309,
    "name": "귀곡촌지도",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 310,
    "name": "마황의뿔",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 311,
    "name": "빙궁의열쇠",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 312,
    "name": "뇌전의조각",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 313,
    "name": "독룡의독낭",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 314,
    "name": "만독림버섯",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 315,
    "name": "설인의털",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 316,
    "name": "백호의발톱",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 317,
    "name": "청룡의비늘",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 318,
    "name": "현무의등껍질",
    "item_type": "misc",
    "sub_type": "기타",
    "price": 300,
    "rarity": 2,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 319,
    "name": "주작의깃털",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 320,
    "name": "기린의뿔조각",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 321,
    "name": "황룡의금빛비늘",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 322,
    "name": "혈월석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 323,
    "name": "뇌전석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 324,
    "name": "빙하석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 325,
    "name": "마황석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 326,
    "name": "용문석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 327,
    "name": "봉황석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 328,
    "name": "설봉석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 329,
    "name": "귀곡석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 330,
    "name": "만독석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 450,
    "rarity": 3,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 331,
    "name": "황금석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 332,
    "name": "칠성석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 333,
    "name": "사신석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 334,
    "name": "제왕석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 335,
    "name": "패왕석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 336,
    "name": "신선석",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 337,
    "name": "강호제일검증서",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 338,
    "name": "천하제일인증",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 339,
    "name": "무림맹인장",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 340,
    "name": "황실밀령",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  },
  {
    "id": 341,
    "name": "사신의초대장",
    "item_type": "rare",
    "sub_type": "기타",
    "price": 600,
    "rarity": 4,
    "stats": "{}",
    "effects": "\"\\ud2b9\\uc218 \\uc544\\uc774\\ud15c\"",
    "description": "특수 아이템"
  }
]
    loaded = items
    for i in loaded:
        i['stats'] = json.loads(i['stats'])
        i['effects'] = json.loads(i['effects'])
        db.add(Item(**i))
    db.commit(); db.close()
    print(f"Seeded {len(loaded)} items! (Total: 350+)")

if __name__ == "__main__":
    seed()
