"""
낙화검심 v0.6 - 무기 150종 (한손무기 + 양손무기 + 방패)
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from app.core.database import SessionLocal, engine, Base
from app.models import Item

def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    if db.query(Item).filter(Item.code == "WPN_SWORD_IRON_01").count() > 0:
        print("v6 weapons already seeded!"); db.close(); return

    weapons = [    {"id": 1000, "code": "WPN_SWORD_철검", "name": "철검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 1, "price": 200, "stack_limit": 1, "stats": {"attack": 10, "defense": 0, "hp": 5}, "description": "철검 - 검계열 mainhand 무기 (희귀도 1성)"},
    {"id": 1001, "code": "WPN_SWORD_강철검", "name": "강철검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 1, "price": 250, "stack_limit": 1, "stats": {"attack": 13, "defense": 0, "hp": 7}, "description": "강철검 - 검계열 mainhand 무기 (희귀도 1성)"},
    {"id": 1002, "code": "WPN_SWORD_청룡검", "name": "청룡검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 1, "price": 300, "stack_limit": 1, "stats": {"attack": 16, "defense": 0, "hp": 9}, "description": "청룡검 - 검계열 mainhand 무기 (희귀도 1성)"},
    {"id": 1003, "code": "WPN_SWORD_벽력검", "name": "벽력검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 2, "price": 450, "stack_limit": 1, "stats": {"attack": 24, "defense": 0, "hp": 11}, "description": "벽력검 - 검계열 mainhand 무기 (희귀도 2성)"},
    {"id": 1004, "code": "WPN_SWORD_혈랑검", "name": "혈랑검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 2, "price": 500, "stack_limit": 1, "stats": {"attack": 27, "defense": 0, "hp": 13}, "description": "혈랑검 - 검계열 mainhand 무기 (희귀도 2성)"},
    {"id": 1005, "code": "WPN_SWORD_마검", "name": "마검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 2, "price": 550, "stack_limit": 1, "stats": {"attack": 30, "defense": 0, "hp": 15}, "description": "마검 - 검계열 mainhand 무기 (희귀도 2성)"},
    {"id": 1006, "code": "WPN_SWORD_성검", "name": "성검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 3, "price": 700, "stack_limit": 1, "stats": {"attack": 38, "defense": 0, "hp": 17}, "description": "성검 - 검계열 mainhand 무기 (희귀도 3성)"},
    {"id": 1007, "code": "WPN_SWORD_용살검", "name": "용살검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 3, "price": 750, "stack_limit": 1, "stats": {"attack": 41, "defense": 0, "hp": 19}, "description": "용살검 - 검계열 mainhand 무기 (희귀도 3성)"},
    {"id": 1008, "code": "WPN_SWORD_신검", "name": "신검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 3, "price": 800, "stack_limit": 1, "stats": {"attack": 44, "defense": 0, "hp": 21}, "description": "신검 - 검계열 mainhand 무기 (희귀도 3성)"},
    {"id": 1009, "code": "WPN_SWORD_혼돈검", "name": "혼돈검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 4, "price": 950, "stack_limit": 1, "stats": {"attack": 52, "defense": 0, "hp": 23}, "description": "혼돈검 - 검계열 mainhand 무기 (희귀도 4성)"},
    {"id": 1010, "code": "WPN_SWORD_폭풍검", "name": "폭풍검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 4, "price": 1000, "stack_limit": 1, "stats": {"attack": 55, "defense": 0, "hp": 25}, "description": "폭풍검 - 검계열 mainhand 무기 (희귀도 4성)"},
    {"id": 1011, "code": "WPN_SWORD_암흑검", "name": "암흑검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 4, "price": 1050, "stack_limit": 1, "stats": {"attack": 58, "defense": 0, "hp": 27}, "description": "암흑검 - 검계열 mainhand 무기 (희귀도 4성)"},
    {"id": 1012, "code": "WPN_SWORD_태양검", "name": "태양검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 5, "price": 1200, "stack_limit": 1, "stats": {"attack": 66, "defense": 0, "hp": 29}, "description": "태양검 - 검계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1013, "code": "WPN_SWORD_냉철검", "name": "냉철검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 5, "price": 1250, "stack_limit": 1, "stats": {"attack": 69, "defense": 0, "hp": 31}, "description": "냉철검 - 검계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1014, "code": "WPN_SWORD_뇌전검", "name": "뇌전검", "item_type": "weapon", "sub_type": "검", "slot": "mainhand", "weapon_type": "sword", "rarity": 5, "price": 1300, "stack_limit": 1, "stats": {"attack": 72, "defense": 0, "hp": 33}, "description": "뇌전검 - 검계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1015, "code": "WPN_BLADE_곡도", "name": "곡도", "item_type": "weapon", "sub_type": "도", "slot": "mainhand", "weapon_type": "blade", "rarity": 1, "price": 200, "stack_limit": 1, "stats": {"attack": 10, "defense": 0, "hp": 5}, "description": "곡도 - 도계열 mainhand 무기 (희귀도 1성)"},
    {"id": 1016, "code": "WPN_BLADE_월도", "name": "월도", "item_type": "weapon", "sub_type": "도", "slot": "mainhand", "weapon_type": "blade", "rarity": 1, "price": 250, "stack_limit": 1, "stats": {"attack": 13, "defense": 0, "hp": 7}, "description": "월도 - 도계열 mainhand 무기 (희귀도 1성)"},
    {"id": 1017, "code": "WPN_BLADE_참마도", "name": "참마도", "item_type": "weapon", "sub_type": "도", "slot": "mainhand", "weapon_type": "blade", "rarity": 2, "price": 400, "stack_limit": 1, "stats": {"attack": 21, "defense": 0, "hp": 9}, "description": "참마도 - 도계열 mainhand 무기 (희귀도 2성)"},
    {"id": 1018, "code": "WPN_BLADE_혈월도", "name": "혈월도", "item_type": "weapon", "sub_type": "도", "slot": "mainhand", "weapon_type": "blade", "rarity": 2, "price": 450, "stack_limit": 1, "stats": {"attack": 24, "defense": 0, "hp": 11}, "description": "혈월도 - 도계열 mainhand 무기 (희귀도 2성)"},
    {"id": 1019, "code": "WPN_BLADE_비황도", "name": "비황도", "item_type": "weapon", "sub_type": "도", "slot": "mainhand", "weapon_type": "blade", "rarity": 3, "price": 600, "stack_limit": 1, "stats": {"attack": 32, "defense": 0, "hp": 13}, "description": "비황도 - 도계열 mainhand 무기 (희귀도 3성)"},
    {"id": 1020, "code": "WPN_BLADE_멸살도", "name": "멸살도", "item_type": "weapon", "sub_type": "도", "slot": "mainhand", "weapon_type": "blade", "rarity": 3, "price": 650, "stack_limit": 1, "stats": {"attack": 35, "defense": 0, "hp": 15}, "description": "멸살도 - 도계열 mainhand 무기 (희귀도 3성)"},
    {"id": 1021, "code": "WPN_BLADE_파천도", "name": "파천도", "item_type": "weapon", "sub_type": "도", "slot": "mainhand", "weapon_type": "blade", "rarity": 4, "price": 800, "stack_limit": 1, "stats": {"attack": 43, "defense": 0, "hp": 17}, "description": "파천도 - 도계열 mainhand 무기 (희귀도 4성)"},
    {"id": 1022, "code": "WPN_BLADE_역린도", "name": "역린도", "item_type": "weapon", "sub_type": "도", "slot": "mainhand", "weapon_type": "blade", "rarity": 4, "price": 850, "stack_limit": 1, "stats": {"attack": 46, "defense": 0, "hp": 19}, "description": "역린도 - 도계열 mainhand 무기 (희귀도 4성)"},
    {"id": 1023, "code": "WPN_BLADE_광룡도", "name": "광룡도", "item_type": "weapon", "sub_type": "도", "slot": "mainhand", "weapon_type": "blade", "rarity": 5, "price": 1000, "stack_limit": 1, "stats": {"attack": 54, "defense": 0, "hp": 21}, "description": "광룡도 - 도계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1024, "code": "WPN_BLADE_폭염도", "name": "폭염도", "item_type": "weapon", "sub_type": "도", "slot": "mainhand", "weapon_type": "blade", "rarity": 5, "price": 1050, "stack_limit": 1, "stats": {"attack": 57, "defense": 0, "hp": 23}, "description": "폭염도 - 도계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1025, "code": "WPN_SPEAR_철창", "name": "철창", "item_type": "weapon", "sub_type": "창", "slot": "mainhand", "weapon_type": "spear", "rarity": 1, "price": 200, "stack_limit": 1, "stats": {"attack": 10, "defense": 0, "hp": 5}, "description": "철창 - 창계열 mainhand 무기 (희귀도 1성)"},
    {"id": 1026, "code": "WPN_SPEAR_강철창", "name": "강철창", "item_type": "weapon", "sub_type": "창", "slot": "mainhand", "weapon_type": "spear", "rarity": 1, "price": 250, "stack_limit": 1, "stats": {"attack": 13, "defense": 0, "hp": 7}, "description": "강철창 - 창계열 mainhand 무기 (희귀도 1성)"},
    {"id": 1027, "code": "WPN_SPEAR_청룡창", "name": "청룡창", "item_type": "weapon", "sub_type": "창", "slot": "mainhand", "weapon_type": "spear", "rarity": 2, "price": 400, "stack_limit": 1, "stats": {"attack": 21, "defense": 0, "hp": 9}, "description": "청룡창 - 창계열 mainhand 무기 (희귀도 2성)"},
    {"id": 1028, "code": "WPN_SPEAR_뇌정창", "name": "뇌정창", "item_type": "weapon", "sub_type": "창", "slot": "mainhand", "weapon_type": "spear", "rarity": 2, "price": 450, "stack_limit": 1, "stats": {"attack": 24, "defense": 0, "hp": 11}, "description": "뇌정창 - 창계열 mainhand 무기 (희귀도 2성)"},
    {"id": 1029, "code": "WPN_SPEAR_혈극창", "name": "혈극창", "item_type": "weapon", "sub_type": "창", "slot": "mainhand", "weapon_type": "spear", "rarity": 3, "price": 600, "stack_limit": 1, "stats": {"attack": 32, "defense": 0, "hp": 13}, "description": "혈극창 - 창계열 mainhand 무기 (희귀도 3성)"},
    {"id": 1030, "code": "WPN_SPEAR_멸룡창", "name": "멸룡창", "item_type": "weapon", "sub_type": "창", "slot": "mainhand", "weapon_type": "spear", "rarity": 3, "price": 650, "stack_limit": 1, "stats": {"attack": 35, "defense": 0, "hp": 15}, "description": "멸룡창 - 창계열 mainhand 무기 (희귀도 3성)"},
    {"id": 1031, "code": "WPN_SPEAR_파멸창", "name": "파멸창", "item_type": "weapon", "sub_type": "창", "slot": "mainhand", "weapon_type": "spear", "rarity": 4, "price": 800, "stack_limit": 1, "stats": {"attack": 43, "defense": 0, "hp": 17}, "description": "파멸창 - 창계열 mainhand 무기 (희귀도 4성)"},
    {"id": 1032, "code": "WPN_SPEAR_신창", "name": "신창", "item_type": "weapon", "sub_type": "창", "slot": "mainhand", "weapon_type": "spear", "rarity": 4, "price": 850, "stack_limit": 1, "stats": {"attack": 46, "defense": 0, "hp": 19}, "description": "신창 - 창계열 mainhand 무기 (희귀도 4성)"},
    {"id": 1033, "code": "WPN_SPEAR_마창", "name": "마창", "item_type": "weapon", "sub_type": "창", "slot": "mainhand", "weapon_type": "spear", "rarity": 5, "price": 1000, "stack_limit": 1, "stats": {"attack": 54, "defense": 0, "hp": 21}, "description": "마창 - 창계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1034, "code": "WPN_SPEAR_혼돈창", "name": "혼돈창", "item_type": "weapon", "sub_type": "창", "slot": "mainhand", "weapon_type": "spear", "rarity": 5, "price": 1050, "stack_limit": 1, "stats": {"attack": 57, "defense": 0, "hp": 23}, "description": "혼돈창 - 창계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1035, "code": "WPN_DAGGER_비수", "name": "비수", "item_type": "weapon", "sub_type": "단검", "slot": "mainhand", "weapon_type": "dagger", "rarity": 1, "price": 200, "stack_limit": 1, "stats": {"attack": 10, "defense": 0, "hp": 5}, "description": "비수 - 단검계열 mainhand 무기 (희귀도 1성)"},
    {"id": 1036, "code": "WPN_DAGGER_독비수", "name": "독비수", "item_type": "weapon", "sub_type": "단검", "slot": "mainhand", "weapon_type": "dagger", "rarity": 2, "price": 350, "stack_limit": 1, "stats": {"attack": 18, "defense": 0, "hp": 7}, "description": "독비수 - 단검계열 mainhand 무기 (희귀도 2성)"},
    {"id": 1037, "code": "WPN_DAGGER_암살검", "name": "암살검", "item_type": "weapon", "sub_type": "단검", "slot": "mainhand", "weapon_type": "dagger", "rarity": 3, "price": 500, "stack_limit": 1, "stats": {"attack": 26, "defense": 0, "hp": 9}, "description": "암살검 - 단검계열 mainhand 무기 (희귀도 3성)"},
    {"id": 1038, "code": "WPN_DAGGER_그림자검", "name": "그림자검", "item_type": "weapon", "sub_type": "단검", "slot": "mainhand", "weapon_type": "dagger", "rarity": 4, "price": 650, "stack_limit": 1, "stats": {"attack": 34, "defense": 0, "hp": 11}, "description": "그림자검 - 단검계열 mainhand 무기 (희귀도 4성)"},
    {"id": 1039, "code": "WPN_DAGGER_멸혼비수", "name": "멸혼비수", "item_type": "weapon", "sub_type": "단검", "slot": "mainhand", "weapon_type": "dagger", "rarity": 5, "price": 800, "stack_limit": 1, "stats": {"attack": 42, "defense": 0, "hp": 13}, "description": "멸혼비수 - 단검계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1040, "code": "WPN_DAGGER_혈뢰비수", "name": "혈뢰비수", "item_type": "weapon", "sub_type": "단검", "slot": "mainhand", "weapon_type": "dagger", "rarity": 5, "price": 850, "stack_limit": 1, "stats": {"attack": 45, "defense": 0, "hp": 15}, "description": "혈뢰비수 - 단검계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1041, "code": "WPN_DAGGER_어둠의이빨", "name": "어둠의이빨", "item_type": "weapon", "sub_type": "단검", "slot": "mainhand", "weapon_type": "dagger", "rarity": 5, "price": 900, "stack_limit": 1, "stats": {"attack": 48, "defense": 0, "hp": 17}, "description": "어둠의이빨 - 단검계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1042, "code": "WPN_DAGGER_명계단검", "name": "명계단검", "item_type": "weapon", "sub_type": "단검", "slot": "mainhand", "weapon_type": "dagger", "rarity": 5, "price": 950, "stack_limit": 1, "stats": {"attack": 51, "defense": 0, "hp": 19}, "description": "명계단검 - 단검계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1043, "code": "WPN_MACE_철퇴", "name": "철퇴", "item_type": "weapon", "sub_type": "둔기", "slot": "mainhand", "weapon_type": "mace", "rarity": 1, "price": 200, "stack_limit": 1, "stats": {"attack": 10, "defense": 0, "hp": 5}, "description": "철퇴 - 둔기계열 mainhand 무기 (희귀도 1성)"},
    {"id": 1044, "code": "WPN_MACE_강철퇴", "name": "강철퇴", "item_type": "weapon", "sub_type": "둔기", "slot": "mainhand", "weapon_type": "mace", "rarity": 2, "price": 350, "stack_limit": 1, "stats": {"attack": 18, "defense": 0, "hp": 7}, "description": "강철퇴 - 둔기계열 mainhand 무기 (희귀도 2성)"},
    {"id": 1045, "code": "WPN_MACE_벽력퇴", "name": "벽력퇴", "item_type": "weapon", "sub_type": "둔기", "slot": "mainhand", "weapon_type": "mace", "rarity": 3, "price": 500, "stack_limit": 1, "stats": {"attack": 26, "defense": 0, "hp": 9}, "description": "벽력퇴 - 둔기계열 mainhand 무기 (희귀도 3성)"},
    {"id": 1046, "code": "WPN_MACE_산붕괴", "name": "산붕괴", "item_type": "weapon", "sub_type": "둔기", "slot": "mainhand", "weapon_type": "mace", "rarity": 4, "price": 650, "stack_limit": 1, "stats": {"attack": 34, "defense": 0, "hp": 11}, "description": "산붕괴 - 둔기계열 mainhand 무기 (희귀도 4성)"},
    {"id": 1047, "code": "WPN_MACE_금강저", "name": "금강저", "item_type": "weapon", "sub_type": "둔기", "slot": "mainhand", "weapon_type": "mace", "rarity": 5, "price": 800, "stack_limit": 1, "stats": {"attack": 42, "defense": 0, "hp": 13}, "description": "금강저 - 둔기계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1048, "code": "WPN_MACE_멸마봉", "name": "멸마봉", "item_type": "weapon", "sub_type": "둔기", "slot": "mainhand", "weapon_type": "mace", "rarity": 5, "price": 850, "stack_limit": 1, "stats": {"attack": 45, "defense": 0, "hp": 15}, "description": "멸마봉 - 둔기계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1049, "code": "WPN_STAFF_목장", "name": "목장", "item_type": "weapon", "sub_type": "지팡이", "slot": "mainhand", "weapon_type": "staff", "rarity": 1, "price": 200, "stack_limit": 1, "stats": {"attack": 10, "defense": 0, "hp": 5}, "description": "목장 - 지팡이계열 mainhand 무기 (희귀도 1성)"},
    {"id": 1050, "code": "WPN_STAFF_철장", "name": "철장", "item_type": "weapon", "sub_type": "지팡이", "slot": "mainhand", "weapon_type": "staff", "rarity": 2, "price": 350, "stack_limit": 1, "stats": {"attack": 18, "defense": 0, "hp": 7}, "description": "철장 - 지팡이계열 mainhand 무기 (희귀도 2성)"},
    {"id": 1051, "code": "WPN_STAFF_마력장", "name": "마력장", "item_type": "weapon", "sub_type": "지팡이", "slot": "mainhand", "weapon_type": "staff", "rarity": 3, "price": 500, "stack_limit": 1, "stats": {"attack": 26, "defense": 0, "hp": 9}, "description": "마력장 - 지팡이계열 mainhand 무기 (희귀도 3성)"},
    {"id": 1052, "code": "WPN_STAFF_현자의지팡이", "name": "현자의지팡이", "item_type": "weapon", "sub_type": "지팡이", "slot": "mainhand", "weapon_type": "staff", "rarity": 4, "price": 650, "stack_limit": 1, "stats": {"attack": 34, "defense": 0, "hp": 11}, "description": "현자의지팡이 - 지팡이계열 mainhand 무기 (희귀도 4성)"},
    {"id": 1053, "code": "WPN_STAFF_대마도사의지팡이", "name": "대마도사의지팡이", "item_type": "weapon", "sub_type": "지팡이", "slot": "mainhand", "weapon_type": "staff", "rarity": 5, "price": 800, "stack_limit": 1, "stats": {"attack": 42, "defense": 0, "hp": 13}, "description": "대마도사의지팡이 - 지팡이계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1054, "code": "WPN_STAFF_천계의지팡이", "name": "천계의지팡이", "item_type": "weapon", "sub_type": "지팡이", "slot": "mainhand", "weapon_type": "staff", "rarity": 5, "price": 850, "stack_limit": 1, "stats": {"attack": 45, "defense": 0, "hp": 15}, "description": "천계의지팡이 - 지팡이계열 mainhand 무기 (희귀도 5성)"},
    {"id": 1055, "code": "WPN_GREATSWORD_철대검", "name": "철대검", "item_type": "weapon", "sub_type": "대검", "slot": "twohand", "weapon_type": "greatsword", "rarity": 1, "price": 200, "stack_limit": 1, "stats": {"attack": 10, "defense": 0, "hp": 5}, "description": "철대검 - 대검계열 twohand 무기 (희귀도 1성)"},
    {"id": 1056, "code": "WPN_GREATSWORD_강철대검", "name": "강철대검", "item_type": "weapon", "sub_type": "대검", "slot": "twohand", "weapon_type": "greatsword", "rarity": 1, "price": 250, "stack_limit": 1, "stats": {"attack": 13, "defense": 0, "hp": 7}, "description": "강철대검 - 대검계열 twohand 무기 (희귀도 1성)"},
    {"id": 1057, "code": "WPN_GREATSWORD_파멸대검", "name": "파멸대검", "item_type": "weapon", "sub_type": "대검", "slot": "twohand", "weapon_type": "greatsword", "rarity": 2, "price": 400, "stack_limit": 1, "stats": {"attack": 21, "defense": 0, "hp": 9}, "description": "파멸대검 - 대검계열 twohand 무기 (희귀도 2성)"},
    {"id": 1058, "code": "WPN_GREATSWORD_혈마대검", "name": "혈마대검", "item_type": "weapon", "sub_type": "대검", "slot": "twohand", "weapon_type": "greatsword", "rarity": 2, "price": 450, "stack_limit": 1, "stats": {"attack": 24, "defense": 0, "hp": 11}, "description": "혈마대검 - 대검계열 twohand 무기 (희귀도 2성)"},
    {"id": 1059, "code": "WPN_GREATSWORD_천벌대검", "name": "천벌대검", "item_type": "weapon", "sub_type": "대검", "slot": "twohand", "weapon_type": "greatsword", "rarity": 3, "price": 600, "stack_limit": 1, "stats": {"attack": 32, "defense": 0, "hp": 13}, "description": "천벌대검 - 대검계열 twohand 무기 (희귀도 3성)"},
    {"id": 1060, "code": "WPN_GREATSWORD_용신대검", "name": "용신대검", "item_type": "weapon", "sub_type": "대검", "slot": "twohand", "weapon_type": "greatsword", "rarity": 3, "price": 650, "stack_limit": 1, "stats": {"attack": 35, "defense": 0, "hp": 15}, "description": "용신대검 - 대검계열 twohand 무기 (희귀도 3성)"},
    {"id": 1061, "code": "WPN_GREATSWORD_멸세대검", "name": "멸세대검", "item_type": "weapon", "sub_type": "대검", "slot": "twohand", "weapon_type": "greatsword", "rarity": 4, "price": 800, "stack_limit": 1, "stats": {"attack": 43, "defense": 0, "hp": 17}, "description": "멸세대검 - 대검계열 twohand 무기 (희귀도 4성)"},
    {"id": 1062, "code": "WPN_GREATSWORD_혼돈대검", "name": "혼돈대검", "item_type": "weapon", "sub_type": "대검", "slot": "twohand", "weapon_type": "greatsword", "rarity": 4, "price": 850, "stack_limit": 1, "stats": {"attack": 46, "defense": 0, "hp": 19}, "description": "혼돈대검 - 대검계열 twohand 무기 (희귀도 4성)"},
    {"id": 1063, "code": "WPN_GREATSWORD_봉인된마검", "name": "봉인된마검", "item_type": "weapon", "sub_type": "대검", "slot": "twohand", "weapon_type": "greatsword", "rarity": 5, "price": 1000, "stack_limit": 1, "stats": {"attack": 54, "defense": 0, "hp": 21}, "description": "봉인된마검 - 대검계열 twohand 무기 (희귀도 5성)"},
    {"id": 1064, "code": "WPN_GREATSWORD_신의대검", "name": "신의대검", "item_type": "weapon", "sub_type": "대검", "slot": "twohand", "weapon_type": "greatsword", "rarity": 5, "price": 1050, "stack_limit": 1, "stats": {"attack": 57, "defense": 0, "hp": 23}, "description": "신의대검 - 대검계열 twohand 무기 (희귀도 5성)"},
    {"id": 1065, "code": "WPN_MOONBLADE_청룡월도", "name": "청룡월도", "item_type": "weapon", "sub_type": "월도", "slot": "twohand", "weapon_type": "moonblade", "rarity": 1, "price": 200, "stack_limit": 1, "stats": {"attack": 10, "defense": 0, "hp": 5}, "description": "청룡월도 - 월도계열 twohand 무기 (희귀도 1성)"},
    {"id": 1066, "code": "WPN_MOONBLADE_혈참월도", "name": "혈참월도", "item_type": "weapon", "sub_type": "월도", "slot": "twohand", "weapon_type": "moonblade", "rarity": 2, "price": 350, "stack_limit": 1, "stats": {"attack": 18, "defense": 0, "hp": 7}, "description": "혈참월도 - 월도계열 twohand 무기 (희귀도 2성)"},
    {"id": 1067, "code": "WPN_MOONBLADE_역린월도", "name": "역린월도", "item_type": "weapon", "sub_type": "월도", "slot": "twohand", "weapon_type": "moonblade", "rarity": 3, "price": 500, "stack_limit": 1, "stats": {"attack": 26, "defense": 0, "hp": 9}, "description": "역린월도 - 월도계열 twohand 무기 (희귀도 3성)"},
    {"id": 1068, "code": "WPN_MOONBLADE_광룡월도", "name": "광룡월도", "item_type": "weapon", "sub_type": "월도", "slot": "twohand", "weapon_type": "moonblade", "rarity": 4, "price": 650, "stack_limit": 1, "stats": {"attack": 34, "defense": 0, "hp": 11}, "description": "광룡월도 - 월도계열 twohand 무기 (희귀도 4성)"},
    {"id": 1069, "code": "WPN_MOONBLADE_멸살월도", "name": "멸살월도", "item_type": "weapon", "sub_type": "월도", "slot": "twohand", "weapon_type": "moonblade", "rarity": 5, "price": 800, "stack_limit": 1, "stats": {"attack": 42, "defense": 0, "hp": 13}, "description": "멸살월도 - 월도계열 twohand 무기 (희귀도 5성)"},
    {"id": 1070, "code": "WPN_LONGSPEAR_용창", "name": "용창", "item_type": "weapon", "sub_type": "장창", "slot": "twohand", "weapon_type": "longspear", "rarity": 1, "price": 200, "stack_limit": 1, "stats": {"attack": 10, "defense": 0, "hp": 5}, "description": "용창 - 장창계열 twohand 무기 (희귀도 1성)"},
    {"id": 1071, "code": "WPN_LONGSPEAR_뇌극창", "name": "뇌극창", "item_type": "weapon", "sub_type": "장창", "slot": "twohand", "weapon_type": "longspear", "rarity": 2, "price": 350, "stack_limit": 1, "stats": {"attack": 18, "defense": 0, "hp": 7}, "description": "뇌극창 - 장창계열 twohand 무기 (희귀도 2성)"},
    {"id": 1072, "code": "WPN_LONGSPEAR_파천창", "name": "파천창", "item_type": "weapon", "sub_type": "장창", "slot": "twohand", "weapon_type": "longspear", "rarity": 3, "price": 500, "stack_limit": 1, "stats": {"attack": 26, "defense": 0, "hp": 9}, "description": "파천창 - 장창계열 twohand 무기 (희귀도 3성)"},
    {"id": 1073, "code": "WPN_LONGSPEAR_혈룡창", "name": "혈룡창", "item_type": "weapon", "sub_type": "장창", "slot": "twohand", "weapon_type": "longspear", "rarity": 4, "price": 650, "stack_limit": 1, "stats": {"attack": 34, "defense": 0, "hp": 11}, "description": "혈룡창 - 장창계열 twohand 무기 (희귀도 4성)"},
    {"id": 1074, "code": "WPN_LONGSPEAR_멸혼창", "name": "멸혼창", "item_type": "weapon", "sub_type": "장창", "slot": "twohand", "weapon_type": "longspear", "rarity": 5, "price": 800, "stack_limit": 1, "stats": {"attack": 42, "defense": 0, "hp": 13}, "description": "멸혼창 - 장창계열 twohand 무기 (희귀도 5성)"},
    {"id": 1075, "code": "WPN_BOW_목궁", "name": "목궁", "item_type": "weapon", "sub_type": "활", "slot": "twohand", "weapon_type": "bow", "rarity": 1, "price": 200, "stack_limit": 1, "stats": {"attack": 10, "defense": 0, "hp": 5}, "description": "목궁 - 활계열 twohand 무기 (희귀도 1성)"},
    {"id": 1076, "code": "WPN_BOW_철궁", "name": "철궁", "item_type": "weapon", "sub_type": "활", "slot": "twohand", "weapon_type": "bow", "rarity": 2, "price": 350, "stack_limit": 1, "stats": {"attack": 18, "defense": 0, "hp": 7}, "description": "철궁 - 활계열 twohand 무기 (희귀도 2성)"},
    {"id": 1077, "code": "WPN_BOW_정령궁", "name": "정령궁", "item_type": "weapon", "sub_type": "활", "slot": "twohand", "weapon_type": "bow", "rarity": 3, "price": 500, "stack_limit": 1, "stats": {"attack": 26, "defense": 0, "hp": 9}, "description": "정령궁 - 활계열 twohand 무기 (희귀도 3성)"},
    {"id": 1078, "code": "WPN_BOW_폭풍궁", "name": "폭풍궁", "item_type": "weapon", "sub_type": "활", "slot": "twohand", "weapon_type": "bow", "rarity": 4, "price": 650, "stack_limit": 1, "stats": {"attack": 34, "defense": 0, "hp": 11}, "description": "폭풍궁 - 활계열 twohand 무기 (희귀도 4성)"},
    {"id": 1079, "code": "WPN_BOW_태양궁", "name": "태양궁", "item_type": "weapon", "sub_type": "활", "slot": "twohand", "weapon_type": "bow", "rarity": 5, "price": 800, "stack_limit": 1, "stats": {"attack": 42, "defense": 0, "hp": 13}, "description": "태양궁 - 활계열 twohand 무기 (희귀도 5성)"},
    {"id": 1080, "code": "WPN_SHIELD_목방패", "name": "목방패", "item_type": "weapon", "sub_type": "방패", "slot": "offhand", "weapon_type": "shield", "rarity": 1, "price": 200, "stack_limit": 1, "stats": {"attack": 10, "defense": 1, "hp": 5}, "description": "목방패 - 방패계열 offhand 무기 (희귀도 1성)"},
    {"id": 1081, "code": "WPN_SHIELD_철방패", "name": "철방패", "item_type": "weapon", "sub_type": "방패", "slot": "offhand", "weapon_type": "shield", "rarity": 1, "price": 250, "stack_limit": 1, "stats": {"attack": 13, "defense": 2, "hp": 7}, "description": "철방패 - 방패계열 offhand 무기 (희귀도 1성)"},
    {"id": 1082, "code": "WPN_SHIELD_강철방패", "name": "강철방패", "item_type": "weapon", "sub_type": "방패", "slot": "offhand", "weapon_type": "shield", "rarity": 2, "price": 400, "stack_limit": 1, "stats": {"attack": 21, "defense": 3, "hp": 9}, "description": "강철방패 - 방패계열 offhand 무기 (희귀도 2성)"},
    {"id": 1083, "code": "WPN_SHIELD_탑방패", "name": "탑방패", "item_type": "weapon", "sub_type": "방패", "slot": "offhand", "weapon_type": "shield", "rarity": 2, "price": 450, "stack_limit": 1, "stats": {"attack": 24, "defense": 4, "hp": 11}, "description": "탑방패 - 방패계열 offhand 무기 (희귀도 2성)"},
    {"id": 1084, "code": "WPN_SHIELD_용비늘방패", "name": "용비늘방패", "item_type": "weapon", "sub_type": "방패", "slot": "offhand", "weapon_type": "shield", "rarity": 3, "price": 600, "stack_limit": 1, "stats": {"attack": 32, "defense": 5, "hp": 13}, "description": "용비늘방패 - 방패계열 offhand 무기 (희귀도 3성)"},
    {"id": 1085, "code": "WPN_SHIELD_성스러운방패", "name": "성스러운방패", "item_type": "weapon", "sub_type": "방패", "slot": "offhand", "weapon_type": "shield", "rarity": 3, "price": 650, "stack_limit": 1, "stats": {"attack": 35, "defense": 6, "hp": 15}, "description": "성스러운방패 - 방패계열 offhand 무기 (희귀도 3성)"},
    {"id": 1086, "code": "WPN_SHIELD_마법방패", "name": "마법방패", "item_type": "weapon", "sub_type": "방패", "slot": "offhand", "weapon_type": "shield", "rarity": 4, "price": 800, "stack_limit": 1, "stats": {"attack": 43, "defense": 7, "hp": 17}, "description": "마법방패 - 방패계열 offhand 무기 (희귀도 4성)"},
    {"id": 1087, "code": "WPN_SHIELD_뼈방패", "name": "뼈방패", "item_type": "weapon", "sub_type": "방패", "slot": "offhand", "weapon_type": "shield", "rarity": 4, "price": 850, "stack_limit": 1, "stats": {"attack": 46, "defense": 8, "hp": 19}, "description": "뼈방패 - 방패계열 offhand 무기 (희귀도 4성)"},
    {"id": 1088, "code": "WPN_SHIELD_어둠의방패", "name": "어둠의방패", "item_type": "weapon", "sub_type": "방패", "slot": "offhand", "weapon_type": "shield", "rarity": 5, "price": 1000, "stack_limit": 1, "stats": {"attack": 54, "defense": 9, "hp": 21}, "description": "어둠의방패 - 방패계열 offhand 무기 (희귀도 5성)"},
    {"id": 1089, "code": "WPN_SHIELD_신의방패", "name": "신의방패", "item_type": "weapon", "sub_type": "방패", "slot": "offhand", "weapon_type": "shield", "rarity": 5, "price": 1050, "stack_limit": 1, "stats": {"attack": 57, "defense": 10, "hp": 23}, "description": "신의방패 - 방패계열 offhand 무기 (희귀도 5성)"}
    ]

    for w in weapons:
        db.add(Item(**w))
    db.commit()
    print(f"v6 weapons seeded: {len(weapons)} weapons (ID 1000~1089)")

if __name__ == "__main__":
    seed()
