"""
낙화검심 - 무공 200종 시드
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from app.core.database import SessionLocal, engine, Base
from app.models import MartialArt

def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    if db.query(MartialArt).count() > 0:
        print("Martial arts already seeded!"); db.close(); return
    arts = [
  {
    "id": 1,
    "name": "낙화십이검",
    "category": "검법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "낙화십이검이 펼쳐집니다!",
    "crit_text": "치명타! 낙화십이검의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 2,
    "name": "청람검식",
    "category": "검법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "청람검식이 펼쳐집니다!",
    "crit_text": "치명타! 청람검식의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 3,
    "name": "벽력검",
    "category": "검법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "벽력검이 펼쳐집니다!",
    "crit_text": "치명타! 벽력검의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 4,
    "name": "잔영검법",
    "category": "검법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "잔영검법이 펼쳐집니다!",
    "crit_text": "치명타! 잔영검법의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 5,
    "name": "무영검",
    "category": "검법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "무영검이 펼쳐집니다!",
    "crit_text": "치명타! 무영검의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 6,
    "name": "칠성검법",
    "category": "검법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 30
    },
    "flavor_text": "칠성검법 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 7,
    "name": "벽수검",
    "category": "검법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.30000000000000004
    },
    "flavor_text": "벽수검! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 8,
    "name": "뇌전검",
    "category": "검법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 5
    },
    "flavor_text": "뇌전검! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 9,
    "name": "한빙검",
    "category": "검법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "한빙검의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 10,
    "name": "폭풍검",
    "category": "검법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "폭풍검의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 11,
    "name": "절영검",
    "category": "검법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "절영검이 펼쳐집니다!",
    "crit_text": "치명타! 절영검의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 12,
    "name": "백보검",
    "category": "검법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "백보검이 펼쳐집니다!",
    "crit_text": "치명타! 백보검의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 13,
    "name": "연화검법",
    "category": "검법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "연화검법이 펼쳐집니다!",
    "crit_text": "치명타! 연화검법의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 14,
    "name": "광풍검",
    "category": "검법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "광풍검이 펼쳐집니다!",
    "crit_text": "치명타! 광풍검의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 15,
    "name": "월하검식",
    "category": "검법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "월하검식이 펼쳐집니다!",
    "crit_text": "치명타! 월하검식의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 16,
    "name": "유성검",
    "category": "검법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 35
    },
    "flavor_text": "유성검 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 17,
    "name": "만파검",
    "category": "검법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.15000000000000002
    },
    "flavor_text": "만파검! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 18,
    "name": "파천검",
    "category": "검법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 2
    },
    "flavor_text": "파천검! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 19,
    "name": "섬전검",
    "category": "검법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 7,
      "dot_duration": 4
    },
    "flavor_text": "섬전검의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 20,
    "name": "일섬검",
    "category": "검법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 7,
      "dot_duration": 4
    },
    "flavor_text": "일섬검의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 21,
    "name": "벽옥검법",
    "category": "검법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "벽옥검법이 펼쳐집니다!",
    "crit_text": "치명타! 벽옥검법의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 22,
    "name": "수라검",
    "category": "검법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "수라검이 펼쳐집니다!",
    "crit_text": "치명타! 수라검의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 23,
    "name": "풍마검",
    "category": "검법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "풍마검이 펼쳐집니다!",
    "crit_text": "치명타! 풍마검의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 24,
    "name": "천잠검",
    "category": "검법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "천잠검이 펼쳐집니다!",
    "crit_text": "치명타! 천잠검의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 25,
    "name": "은사검",
    "category": "검법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "은사검이 펼쳐집니다!",
    "crit_text": "치명타! 은사검의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 26,
    "name": "만월검",
    "category": "검법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 20
    },
    "flavor_text": "만월검 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 27,
    "name": "뇌검",
    "category": "검법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.2
    },
    "flavor_text": "뇌검! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 28,
    "name": "대라검",
    "category": "검법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 3
    },
    "flavor_text": "대라검! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 29,
    "name": "백사검",
    "category": "검법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 9,
      "dot_duration": 5
    },
    "flavor_text": "백사검의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 30,
    "name": "파랑검",
    "category": "검법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 9,
      "dot_duration": 5
    },
    "flavor_text": "파랑검의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 31,
    "name": "소상검",
    "category": "검법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "소상검이 펼쳐집니다!",
    "crit_text": "치명타! 소상검의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 32,
    "name": "벽운검",
    "category": "검법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "벽운검이 펼쳐집니다!",
    "crit_text": "치명타! 벽운검의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 33,
    "name": "청운검법",
    "category": "검법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "청운검법이 펼쳐집니다!",
    "crit_text": "치명타! 청운검법의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 34,
    "name": "옥소검",
    "category": "검법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "옥소검이 펼쳐집니다!",
    "crit_text": "치명타! 옥소검의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 35,
    "name": "잠룡검",
    "category": "검법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "잠룡검이 펼쳐집니다!",
    "crit_text": "치명타! 잠룡검의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 36,
    "name": "파멸검",
    "category": "검법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 25
    },
    "flavor_text": "파멸검 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 37,
    "name": "무진검",
    "category": "검법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.25
    },
    "flavor_text": "무진검! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 38,
    "name": "회천검",
    "category": "검법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 4
    },
    "flavor_text": "회천검! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 39,
    "name": "절도검",
    "category": "검법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 11,
      "dot_duration": 6
    },
    "flavor_text": "절도검의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 40,
    "name": "은혼검",
    "category": "검법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 11,
      "dot_duration": 6
    },
    "flavor_text": "은혼검의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 41,
    "name": "광혈도",
    "category": "도법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "광혈도이 펼쳐집니다!",
    "crit_text": "치명타! 광혈도의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 42,
    "name": "파천도법",
    "category": "도법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "파천도법이 펼쳐집니다!",
    "crit_text": "치명타! 파천도법의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 43,
    "name": "만악도",
    "category": "도법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "만악도이 펼쳐집니다!",
    "crit_text": "치명타! 만악도의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 44,
    "name": "역천도",
    "category": "도법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "역천도이 펼쳐집니다!",
    "crit_text": "치명타! 역천도의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 45,
    "name": "흑월도",
    "category": "도법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "흑월도이 펼쳐집니다!",
    "crit_text": "치명타! 흑월도의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 46,
    "name": "파사도",
    "category": "도법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 30
    },
    "flavor_text": "파사도 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 47,
    "name": "혈령도",
    "category": "도법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.30000000000000004
    },
    "flavor_text": "혈령도! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 48,
    "name": "광룡도",
    "category": "도법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 5
    },
    "flavor_text": "광룡도! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 49,
    "name": "마영도",
    "category": "도법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "마영도의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 50,
    "name": "사혼도",
    "category": "도법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "사혼도의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 51,
    "name": "귀왕도",
    "category": "도법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "귀왕도이 펼쳐집니다!",
    "crit_text": "치명타! 귀왕도의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 52,
    "name": "절명도",
    "category": "도법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "절명도이 펼쳐집니다!",
    "crit_text": "치명타! 절명도의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 53,
    "name": "대파도",
    "category": "도법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "대파도이 펼쳐집니다!",
    "crit_text": "치명타! 대파도의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 54,
    "name": "참마도",
    "category": "도법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "참마도이 펼쳐집니다!",
    "crit_text": "치명타! 참마도의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 55,
    "name": "흑풍도",
    "category": "도법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "흑풍도이 펼쳐집니다!",
    "crit_text": "치명타! 흑풍도의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 56,
    "name": "만파도",
    "category": "도법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 35
    },
    "flavor_text": "만파도 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 57,
    "name": "역린도",
    "category": "도법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.15000000000000002
    },
    "flavor_text": "역린도! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 58,
    "name": "폭열도",
    "category": "도법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 2
    },
    "flavor_text": "폭열도! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 59,
    "name": "참혼도",
    "category": "도법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 7,
      "dot_duration": 4
    },
    "flavor_text": "참혼도의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 60,
    "name": "백귀도",
    "category": "도법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 7,
      "dot_duration": 4
    },
    "flavor_text": "백귀도의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 61,
    "name": "살풍도",
    "category": "도법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "살풍도이 펼쳐집니다!",
    "crit_text": "치명타! 살풍도의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 62,
    "name": "혈참도",
    "category": "도법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "혈참도이 펼쳐집니다!",
    "crit_text": "치명타! 혈참도의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 63,
    "name": "대도결",
    "category": "도법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "대도결이 펼쳐집니다!",
    "crit_text": "치명타! 대도결의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 64,
    "name": "광살도",
    "category": "도법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "광살도이 펼쳐집니다!",
    "crit_text": "치명타! 광살도의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 65,
    "name": "파멸도",
    "category": "도법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "파멸도이 펼쳐집니다!",
    "crit_text": "치명타! 파멸도의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 66,
    "name": "벽력장",
    "category": "장법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "벽력장이 펼쳐집니다!",
    "crit_text": "치명타! 벽력장의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 67,
    "name": "낙화장",
    "category": "장법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "낙화장이 펼쳐집니다!",
    "crit_text": "치명타! 낙화장의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 68,
    "name": "대력장",
    "category": "장법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "대력장이 펼쳐집니다!",
    "crit_text": "치명타! 대력장의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 69,
    "name": "금강장",
    "category": "장법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "금강장이 펼쳐집니다!",
    "crit_text": "치명타! 금강장의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 70,
    "name": "철사장",
    "category": "장법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "철사장이 펼쳐집니다!",
    "crit_text": "치명타! 철사장의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 71,
    "name": "소혼장",
    "category": "장법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 30
    },
    "flavor_text": "소혼장 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 72,
    "name": "천뢰장",
    "category": "장법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.30000000000000004
    },
    "flavor_text": "천뢰장! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 73,
    "name": "와룡장",
    "category": "장법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 5
    },
    "flavor_text": "와룡장! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 74,
    "name": "팽배장",
    "category": "장법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "팽배장의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 75,
    "name": "옥녀장",
    "category": "장법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "옥녀장의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 76,
    "name": "현음장",
    "category": "장법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "현음장이 펼쳐집니다!",
    "crit_text": "치명타! 현음장의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 77,
    "name": "파산장",
    "category": "장법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "파산장이 펼쳐집니다!",
    "crit_text": "치명타! 파산장의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 78,
    "name": "백보장",
    "category": "장법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "백보장이 펼쳐집니다!",
    "crit_text": "치명타! 백보장의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 79,
    "name": "염마장",
    "category": "장법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "염마장이 펼쳐집니다!",
    "crit_text": "치명타! 염마장의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 80,
    "name": "통천장",
    "category": "장법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "통천장이 펼쳐집니다!",
    "crit_text": "치명타! 통천장의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 81,
    "name": "대붕장",
    "category": "장법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 35
    },
    "flavor_text": "대붕장 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 82,
    "name": "와환장",
    "category": "장법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.15000000000000002
    },
    "flavor_text": "와환장! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 83,
    "name": "흑사장",
    "category": "장법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 2
    },
    "flavor_text": "흑사장! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 84,
    "name": "혈수장",
    "category": "장법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 7,
      "dot_duration": 4
    },
    "flavor_text": "혈수장의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 85,
    "name": "대비장",
    "category": "장법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 7,
      "dot_duration": 4
    },
    "flavor_text": "대비장의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 86,
    "name": "용상장",
    "category": "장법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "용상장이 펼쳐집니다!",
    "crit_text": "치명타! 용상장의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 87,
    "name": "봉황장",
    "category": "장법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "봉황장이 펼쳐집니다!",
    "crit_text": "치명타! 봉황장의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 88,
    "name": "천산장",
    "category": "장법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "천산장이 펼쳐집니다!",
    "crit_text": "치명타! 천산장의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 89,
    "name": "일양장",
    "category": "장법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "일양장이 펼쳐집니다!",
    "crit_text": "치명타! 일양장의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 90,
    "name": "파공장",
    "category": "장법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "파공장이 펼쳐집니다!",
    "crit_text": "치명타! 파공장의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 91,
    "name": "태산권",
    "category": "권법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "태산권이 펼쳐집니다!",
    "crit_text": "치명타! 태산권의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 92,
    "name": "나한권",
    "category": "권법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "나한권이 펼쳐집니다!",
    "crit_text": "치명타! 나한권의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 93,
    "name": "취권",
    "category": "권법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "취권이 펼쳐집니다!",
    "crit_text": "치명타! 취권의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 94,
    "name": "매화권",
    "category": "권법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "매화권이 펼쳐집니다!",
    "crit_text": "치명타! 매화권의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 95,
    "name": "와호권",
    "category": "권법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "와호권이 펼쳐집니다!",
    "crit_text": "치명타! 와호권의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 96,
    "name": "칠성권",
    "category": "권법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 30
    },
    "flavor_text": "칠성권 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 97,
    "name": "백보권",
    "category": "권법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.30000000000000004
    },
    "flavor_text": "백보권! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 98,
    "name": "통배권",
    "category": "권법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 5
    },
    "flavor_text": "통배권! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 99,
    "name": "금강권",
    "category": "권법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "금강권의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 100,
    "name": "파옥권",
    "category": "권법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "파옥권의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 101,
    "name": "용호권",
    "category": "권법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "용호권이 펼쳐집니다!",
    "crit_text": "치명타! 용호권의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 102,
    "name": "봉미권",
    "category": "권법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "봉미권이 펼쳐집니다!",
    "crit_text": "치명타! 봉미권의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 103,
    "name": "사자권",
    "category": "권법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "사자권이 펼쳐집니다!",
    "crit_text": "치명타! 사자권의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 104,
    "name": "영춘권",
    "category": "권법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "영춘권이 펼쳐집니다!",
    "crit_text": "치명타! 영춘권의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 105,
    "name": "철선권",
    "category": "권법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "철선권이 펼쳐집니다!",
    "crit_text": "치명타! 철선권의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 106,
    "name": "무영권",
    "category": "권법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 35
    },
    "flavor_text": "무영권 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 107,
    "name": "뇌음권",
    "category": "권법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.15000000000000002
    },
    "flavor_text": "뇌음권! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 108,
    "name": "팔괘권",
    "category": "권법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 2
    },
    "flavor_text": "팔괘권! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 109,
    "name": "대붕권",
    "category": "권법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 7,
      "dot_duration": 4
    },
    "flavor_text": "대붕권의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 110,
    "name": "쇄혼권",
    "category": "권법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 7,
      "dot_duration": 4
    },
    "flavor_text": "쇄혼권의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 111,
    "name": "일양지",
    "category": "지법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "일양지이 펼쳐집니다!",
    "crit_text": "치명타! 일양지의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 112,
    "name": "탄지신통",
    "category": "지법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "탄지신통이 펼쳐집니다!",
    "crit_text": "치명타! 탄지신통의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 113,
    "name": "금강지",
    "category": "지법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "금강지이 펼쳐집니다!",
    "crit_text": "치명타! 금강지의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 114,
    "name": "섬전지",
    "category": "지법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "섬전지이 펼쳐집니다!",
    "crit_text": "치명타! 섬전지의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 115,
    "name": "옥녀지",
    "category": "지법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "옥녀지이 펼쳐집니다!",
    "crit_text": "치명타! 옥녀지의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 116,
    "name": "대력지",
    "category": "지법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 30
    },
    "flavor_text": "대력지 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 117,
    "name": "벽력지",
    "category": "지법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.30000000000000004
    },
    "flavor_text": "벽력지! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 118,
    "name": "파혈지",
    "category": "지법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 5
    },
    "flavor_text": "파혈지! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 119,
    "name": "참마지",
    "category": "지법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "참마지의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 120,
    "name": "쇄혼지",
    "category": "지법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "쇄혼지의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 121,
    "name": "봉황지",
    "category": "지법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "봉황지이 펼쳐집니다!",
    "crit_text": "치명타! 봉황지의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 122,
    "name": "잠룡지",
    "category": "지법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "잠룡지이 펼쳐집니다!",
    "crit_text": "치명타! 잠룡지의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 123,
    "name": "비연지",
    "category": "지법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "비연지이 펼쳐집니다!",
    "crit_text": "치명타! 비연지의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 124,
    "name": "독룡지",
    "category": "지법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "독룡지이 펼쳐집니다!",
    "crit_text": "치명타! 독룡지의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 125,
    "name": "한빙지",
    "category": "지법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "한빙지이 펼쳐집니다!",
    "crit_text": "치명타! 한빙지의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 126,
    "name": "섬멸지",
    "category": "지법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 35
    },
    "flavor_text": "섬멸지 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 127,
    "name": "멸혼지",
    "category": "지법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.15000000000000002
    },
    "flavor_text": "멸혼지! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 128,
    "name": "파천지",
    "category": "지법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 2
    },
    "flavor_text": "파천지! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 129,
    "name": "절맥지",
    "category": "지법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 7,
      "dot_duration": 4
    },
    "flavor_text": "절맥지의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 130,
    "name": "칠살지",
    "category": "지법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 7,
      "dot_duration": 4
    },
    "flavor_text": "칠살지의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 131,
    "name": "만천화우",
    "category": "암기",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "만천화우이 펼쳐집니다!",
    "crit_text": "치명타! 만천화우의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 132,
    "name": "벽력표",
    "category": "암기",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "벽력표이 펼쳐집니다!",
    "crit_text": "치명타! 벽력표의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 133,
    "name": "비엽침",
    "category": "암기",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "비엽침이 펼쳐집니다!",
    "crit_text": "치명타! 비엽침의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 134,
    "name": "탈혼침",
    "category": "암기",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "탈혼침이 펼쳐집니다!",
    "crit_text": "치명타! 탈혼침의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 135,
    "name": "만독침",
    "category": "암기",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "만독침이 펼쳐집니다!",
    "crit_text": "치명타! 만독침의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 136,
    "name": "철질려",
    "category": "암기",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 30
    },
    "flavor_text": "철질려 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 137,
    "name": "오망표",
    "category": "암기",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.30000000000000004
    },
    "flavor_text": "오망표! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 138,
    "name": "뼈분쇄침",
    "category": "암기",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 5
    },
    "flavor_text": "뼈분쇄침! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 139,
    "name": "칠절표",
    "category": "암기",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "칠절표의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 140,
    "name": "낙화표",
    "category": "암기",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "낙화표의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 141,
    "name": "독표",
    "category": "암기",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "독표이 펼쳐집니다!",
    "crit_text": "치명타! 독표의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 142,
    "name": "비수",
    "category": "암기",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "비수이 펼쳐집니다!",
    "crit_text": "치명타! 비수의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 143,
    "name": "은사침",
    "category": "암기",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "은사침이 펼쳐집니다!",
    "crit_text": "치명타! 은사침의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 144,
    "name": "멸혼표",
    "category": "암기",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "멸혼표이 펼쳐집니다!",
    "crit_text": "치명타! 멸혼표의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 145,
    "name": "무영침",
    "category": "암기",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "무영침이 펼쳐집니다!",
    "crit_text": "치명타! 무영침의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 146,
    "name": "제운종",
    "category": "경공",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "제운종이 펼쳐집니다!",
    "crit_text": "치명타! 제운종의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 147,
    "name": "비연보",
    "category": "경공",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "비연보이 펼쳐집니다!",
    "crit_text": "치명타! 비연보의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 148,
    "name": "만화경공",
    "category": "경공",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "만화경공이 펼쳐집니다!",
    "crit_text": "치명타! 만화경공의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 149,
    "name": "벽호보",
    "category": "경공",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "벽호보이 펼쳐집니다!",
    "crit_text": "치명타! 벽호보의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 150,
    "name": "잠영보법",
    "category": "경공",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "잠영보법이 펼쳐집니다!",
    "crit_text": "치명타! 잠영보법의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 151,
    "name": "등천종",
    "category": "경공",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 30
    },
    "flavor_text": "등천종 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 152,
    "name": "공중답보",
    "category": "경공",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.30000000000000004
    },
    "flavor_text": "공중답보! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 153,
    "name": "천리행",
    "category": "경공",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 5
    },
    "flavor_text": "천리행! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 154,
    "name": "유성추월",
    "category": "경공",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "유성추월의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 155,
    "name": "무영보",
    "category": "경공",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "무영보의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 156,
    "name": "비천보",
    "category": "경공",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "비천보이 펼쳐집니다!",
    "crit_text": "치명타! 비천보의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 157,
    "name": "전광보",
    "category": "경공",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "전광보이 펼쳐집니다!",
    "crit_text": "치명타! 전광보의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 158,
    "name": "쇄영보",
    "category": "경공",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "쇄영보이 펼쳐집니다!",
    "crit_text": "치명타! 쇄영보의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 159,
    "name": "허공답보",
    "category": "경공",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "허공답보이 펼쳐집니다!",
    "crit_text": "치명타! 허공답보의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 160,
    "name": "풍신보",
    "category": "경공",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "풍신보이 펼쳐집니다!",
    "crit_text": "치명타! 풍신보의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 161,
    "name": "금강불괴",
    "category": "호신강기",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "금강불괴이 펼쳐집니다!",
    "crit_text": "치명타! 금강불괴의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 162,
    "name": "현빙호체",
    "category": "호신강기",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "현빙호체이 펼쳐집니다!",
    "crit_text": "치명타! 현빙호체의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 163,
    "name": "대라강기",
    "category": "호신강기",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "대라강기이 펼쳐집니다!",
    "crit_text": "치명타! 대라강기의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 164,
    "name": "철포삼",
    "category": "호신강기",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "철포삼이 펼쳐집니다!",
    "crit_text": "치명타! 철포삼의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 165,
    "name": "불괴신공",
    "category": "호신강기",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "불괴신공이 펼쳐집니다!",
    "crit_text": "치명타! 불괴신공의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 166,
    "name": "벽력호체",
    "category": "호신강기",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 30
    },
    "flavor_text": "벽력호체 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 167,
    "name": "천잠강기",
    "category": "호신강기",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.30000000000000004
    },
    "flavor_text": "천잠강기! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 168,
    "name": "금종조",
    "category": "호신강기",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 5
    },
    "flavor_text": "금종조! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 169,
    "name": "혈마강기",
    "category": "호신강기",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "혈마강기의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 170,
    "name": "옥녀호체",
    "category": "호신강기",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "옥녀호체의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 171,
    "name": "구양신공",
    "category": "내공심법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "구양신공이 펼쳐집니다!",
    "crit_text": "치명타! 구양신공의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 172,
    "name": "구음진경",
    "category": "내공심법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "구음진경이 펼쳐집니다!",
    "crit_text": "치명타! 구음진경의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 173,
    "name": "자하신공",
    "category": "내공심법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "자하신공이 펼쳐집니다!",
    "crit_text": "치명타! 자하신공의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 174,
    "name": "태을진기",
    "category": "내공심법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "태을진기이 펼쳐집니다!",
    "crit_text": "치명타! 태을진기의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 175,
    "name": "북명신공",
    "category": "내공심법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "북명신공이 펼쳐집니다!",
    "crit_text": "치명타! 북명신공의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 176,
    "name": "혼원일기공",
    "category": "내공심법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 30
    },
    "flavor_text": "혼원일기공 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 177,
    "name": "소무상공",
    "category": "내공심법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.30000000000000004
    },
    "flavor_text": "소무상공! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 178,
    "name": "현공대법",
    "category": "내공심법",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 5
    },
    "flavor_text": "현공대법! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 179,
    "name": "벽력진기",
    "category": "내공심법",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "벽력진기의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 180,
    "name": "선천공",
    "category": "내공심법",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "선천공의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 181,
    "name": "무상대법",
    "category": "내공심법",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "무상대법이 펼쳐집니다!",
    "crit_text": "치명타! 무상대법의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 182,
    "name": "역근경",
    "category": "내공심법",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "역근경이 펼쳐집니다!",
    "crit_text": "치명타! 역근경의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 183,
    "name": "태현경",
    "category": "내공심법",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "태현경이 펼쳐집니다!",
    "crit_text": "치명타! 태현경의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 184,
    "name": "만법귀종",
    "category": "내공심법",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "만법귀종이 펼쳐집니다!",
    "crit_text": "치명타! 만법귀종의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 185,
    "name": "건곤대나이",
    "category": "내공심법",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "건곤대나이이 펼쳐집니다!",
    "crit_text": "치명타! 건곤대나이의 진정한 위력이 폭발합니다!",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 186,
    "name": "칠성검진",
    "category": "진법/합격기",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "칠성검진이 펼쳐집니다!",
    "crit_text": "치명타! 칠성검진의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 187,
    "name": "팔문금쇄진",
    "category": "진법/합격기",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "팔문금쇄진이 펼쳐집니다!",
    "crit_text": "치명타! 팔문금쇄진의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 188,
    "name": "천라지망",
    "category": "진법/합격기",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "천라지망이 펼쳐집니다!",
    "crit_text": "치명타! 천라지망의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 189,
    "name": "사상진",
    "category": "진법/합격기",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "사상진이 펼쳐집니다!",
    "crit_text": "치명타! 사상진의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 190,
    "name": "양의진",
    "category": "진법/합격기",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "양의진이 펼쳐집니다!",
    "crit_text": "치명타! 양의진의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 191,
    "name": "육합진",
    "category": "진법/합격기",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 30
    },
    "flavor_text": "육합진 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 192,
    "name": "태극진",
    "category": "진법/합격기",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.30000000000000004
    },
    "flavor_text": "태극진! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 193,
    "name": "혼원진",
    "category": "진법/합격기",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 5
    },
    "flavor_text": "혼원진! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 194,
    "name": "십절진",
    "category": "진법/합격기",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "십절진의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 195,
    "name": "금강복마진",
    "category": "진법/합격기",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "금강복마진의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 196,
    "name": "칠절독",
    "category": "독공/의술",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "칠절독이 펼쳐집니다!",
    "crit_text": "치명타! 칠절독의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 197,
    "name": "만사심독",
    "category": "독공/의술",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "만사심독이 펼쳐집니다!",
    "crit_text": "치명타! 만사심독의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 198,
    "name": "백화연정독",
    "category": "독공/의술",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "백화연정독이 펼쳐집니다!",
    "crit_text": "치명타! 백화연정독의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 199,
    "name": "빙백독장",
    "category": "독공/의술",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "빙백독장이 펼쳐집니다!",
    "crit_text": "치명타! 빙백독장의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 200,
    "name": "칠보해독술",
    "category": "독공/의술",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "칠보해독술이 펼쳐집니다!",
    "crit_text": "치명타! 칠보해독술의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 201,
    "name": "회춘의술",
    "category": "독공/의술",
    "stage_required": "초절정",
    "damage_multiplier": 2.0,
    "mp_cost": 40,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "heal",
    "effect_params": {
      "heal_amount": 30
    },
    "flavor_text": "회춘의술 — 온몸에 따뜻한 기운이 퍼집니다.",
    "crit_text": "",
    "rarity": 3,
    "faction_id": None
  },
  {
    "id": 202,
    "name": "오독비술",
    "category": "독공/의술",
    "stage_required": "화경",
    "damage_multiplier": 2.2,
    "mp_cost": 45,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "buff",
    "effect_params": {
      "buff_type": "atk",
      "buff_amount": 0.30000000000000004
    },
    "flavor_text": "오독비술! 전투의 흐름이 바뀝니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 203,
    "name": "혈마독",
    "category": "독공/의술",
    "stage_required": "현경",
    "damage_multiplier": 2.4,
    "mp_cost": 50,
    "cooldown_ticks": 6,
    "cast_time_ticks": 1,
    "effect_type": "debuff",
    "effect_params": {
      "debuff_type": "def",
      "debuff_amount": 5
    },
    "flavor_text": "혈마독! 적의 움직임이 둔해집니다!",
    "crit_text": "",
    "rarity": 4,
    "faction_id": None
  },
  {
    "id": 204,
    "name": "부사독",
    "category": "독공/의술",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "부사독의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 205,
    "name": "천향두단산",
    "category": "독공/의술",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "dot",
    "effect_params": {
      "dot_dmg": 5,
      "dot_duration": 3
    },
    "flavor_text": "천향두단산의 잔향이 적을 갉아먹습니다!",
    "crit_text": "",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 206,
    "name": "벽해조생곡",
    "category": "악기공/기문",
    "stage_required": "입문",
    "damage_multiplier": 1.0,
    "mp_cost": 15,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "벽해조생곡이 펼쳐집니다!",
    "crit_text": "치명타! 벽해조생곡의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 207,
    "name": "천마금",
    "category": "악기공/기문",
    "stage_required": "소성",
    "damage_multiplier": 1.2,
    "mp_cost": 20,
    "cooldown_ticks": 3,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "천마금이 펼쳐집니다!",
    "crit_text": "치명타! 천마금의 진정한 위력이 폭발합니다!",
    "rarity": 1,
    "faction_id": None
  },
  {
    "id": 208,
    "name": "소혼곡",
    "category": "악기공/기문",
    "stage_required": "대성",
    "damage_multiplier": 1.4,
    "mp_cost": 25,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "소혼곡이 펼쳐집니다!",
    "crit_text": "치명타! 소혼곡의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 209,
    "name": "칠현금법",
    "category": "악기공/기문",
    "stage_required": "원만",
    "damage_multiplier": 1.6,
    "mp_cost": 30,
    "cooldown_ticks": 4,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "칠현금법이 펼쳐집니다!",
    "crit_text": "치명타! 칠현금법의 진정한 위력이 폭발합니다!",
    "rarity": 2,
    "faction_id": None
  },
  {
    "id": 210,
    "name": "난화곡",
    "category": "악기공/기문",
    "stage_required": "절정",
    "damage_multiplier": 1.8,
    "mp_cost": 35,
    "cooldown_ticks": 5,
    "cast_time_ticks": 1,
    "effect_type": "damage",
    "effect_params": {},
    "flavor_text": "난화곡이 펼쳐집니다!",
    "crit_text": "치명타! 난화곡의 진정한 위력이 폭발합니다!",
    "rarity": 3,
    "faction_id": None
  }
]
    for a in arts:
        db.add(MartialArt(**a))
    db.commit(); db.close()
    print(f"Seeded {len(arts)} martial arts!")

if __name__ == "__main__":
    seed()
