"""
낙화검심 v0.6.1 - 몬스터 80-200 구간 보강 + level_required 반영
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from app.core.database import SessionLocal, engine, Base
from app.models import Monster, Item

def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    if db.query(Monster).filter(Monster.id == 200).count() > 0:
        print("v6.1 monsters already seeded!"); db.close(); return

    # 몬스터 ID 200~299 대역 사용 (신규)
    monsters = [{"id": 200, "name": "암흑마법사", "description": "검은 로브를 걸친 마법사가 손끝에서 어둠의 화염을 피워올린다.", "hp": 2500, "max_hp": 2500, "attack": 75, "defense": 35, "speed": 40, "exp_reward": 1800, "gold_reward": 450, "min_level": 80, "max_level": 100, "drop_table": [{"item_code": "WPN_STAFF_마력장", "rate": 0.08, "min_qty": 1, "max_qty": 1}, {"item_code": "ARM_CLOAK_천망토", "rate": 0.06, "min_qty": 1, "max_qty": 1}, {"item_code": "CONS_ENCHANT_STONE", "rate": 0.12, "min_qty": 1, "max_qty": 3}], "attack_templates": ["암흑마법사의 강력한 일격!", "암흑마법사이(가) 맹렬히 공격한다!"], "death_template": "암흑마법사이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 201, "name": "강철골렘", "description": "녹슨 강철로 만들어진 거대한 골렘이 묵직한 발걸음으로 다가온다.", "hp": 3500, "max_hp": 3500, "attack": 60, "defense": 60, "speed": 15, "exp_reward": 2000, "gold_reward": 500, "min_level": 85, "max_level": 110, "drop_table": [{"item_code": "ARM_CHEST_철갑옷", "rate": 0.1, "min_qty": 1, "max_qty": 1}, {"item_code": "ARM_HEAD_철투구", "rate": 0.08, "min_qty": 1, "max_qty": 1}, {"item_code": "CONS_PROTECT_STONE", "rate": 0.05, "min_qty": 1, "max_qty": 2}], "attack_templates": ["강철골렘의 강력한 일격!", "강철골렘이(가) 맹렬히 공격한다!"], "death_template": "강철골렘이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 202, "name": "그림자암살자", "description": "그림자 속에서 번뜩이는 단검만이 그의 존재를 알린다.", "hp": 1800, "max_hp": 1800, "attack": 90, "defense": 20, "speed": 60, "exp_reward": 2200, "gold_reward": 380, "min_level": 90, "max_level": 115, "drop_table": [{"item_code": "WPN_DAGGER_암살검", "rate": 0.1, "min_qty": 1, "max_qty": 1}, {"item_code": "ARM_FEET_비룡신발", "rate": 0.07, "min_qty": 1, "max_qty": 1}], "attack_templates": ["그림자암살자의 강력한 일격!", "그림자암살자이(가) 맹렬히 공격한다!"], "death_template": "그림자암살자이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 203, "name": "타락한성기사", "description": "한때 성스러웠을 기사가 어둠에 물들어 검은 갑옷을 입고 있다.", "hp": 4500, "max_hp": 4500, "attack": 85, "defense": 50, "speed": 30, "exp_reward": 2800, "gold_reward": 650, "min_level": 100, "max_level": 130, "drop_table": [{"item_code": "WPN_SWORD_암흑검", "rate": 0.08, "min_qty": 1, "max_qty": 1}, {"item_code": "ARM_CHEST_강철갑옷", "rate": 0.1, "min_qty": 1, "max_qty": 1}], "attack_templates": ["타락한성기사의 강력한 일격!", "타락한성기사이(가) 맹렬히 공격한다!"], "death_template": "타락한성기사이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 204, "name": "폭풍샤먼", "description": "번개를 몸에 두른 샤먼이 천둥의 주문을 외운다.", "hp": 2800, "max_hp": 2800, "attack": 100, "defense": 25, "speed": 45, "exp_reward": 3000, "gold_reward": 550, "min_level": 105, "max_level": 135, "drop_table": [{"item_code": "WPN_STAFF_마력장", "rate": 0.09, "min_qty": 1, "max_qty": 1}, {"item_code": "CONS_FULL_HEAL", "rate": 0.03, "min_qty": 1, "max_qty": 2}], "attack_templates": ["폭풍샤먼의 강력한 일격!", "폭풍샤먼이(가) 맹렬히 공격한다!"], "death_template": "폭풍샤먼이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 205, "name": "지옥사냥개", "description": "불타는 눈을 가진 거대한 개가 지옥불을 뿜어낸다.", "hp": 3200, "max_hp": 3200, "attack": 80, "defense": 30, "speed": 55, "exp_reward": 2600, "gold_reward": 480, "min_level": 110, "max_level": 140, "drop_table": [{"item_code": "ARM_HANDS_용발톱장갑", "rate": 0.08, "min_qty": 1, "max_qty": 1}, {"item_code": "CONS_HP_POT_EL", "rate": 0.1, "min_qty": 1, "max_qty": 3}], "attack_templates": ["지옥사냥개의 강력한 일격!", "지옥사냥개이(가) 맹렬히 공격한다!"], "death_template": "지옥사냥개이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 206, "name": "혈마법사", "description": "피로 그린 마법진 위에 선 마법사가 섬뜩한 미소를 짓는다.", "hp": 5000, "max_hp": 5000, "attack": 110, "defense": 40, "speed": 35, "exp_reward": 3800, "gold_reward": 800, "min_level": 130, "max_level": 160, "drop_table": [{"item_code": "WPN_STAFF_대마도사의지팡이", "rate": 0.06, "min_qty": 1, "max_qty": 1}, {"item_code": "CONS_ATK_BUFF", "rate": 0.08, "min_qty": 1, "max_qty": 2}], "attack_templates": ["혈마법사의 강력한 일격!", "혈마법사이(가) 맹렬히 공격한다!"], "death_template": "혈마법사이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 207, "name": "수정거미", "description": "보석처럼 반짝이는 거대한 거미가 독액을 흘린다.", "hp": 3800, "max_hp": 3800, "attack": 95, "defense": 45, "speed": 50, "exp_reward": 3400, "gold_reward": 700, "min_level": 135, "max_level": 165, "drop_table": [{"item_code": "ARM_NECKLACE_마력목걸이", "rate": 0.07, "min_qty": 1, "max_qty": 1}, {"item_code": "CONS_ANTIDOTE", "rate": 0.15, "min_qty": 1, "max_qty": 3}], "attack_templates": ["수정거미의 강력한 일격!", "수정거미이(가) 맹렬히 공격한다!"], "death_template": "수정거미이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 208, "name": "고대수호자", "description": "무너진 신전을 지키는 석상이 눈을 뜨고 움직이기 시작한다.", "hp": 6000, "max_hp": 6000, "attack": 75, "defense": 70, "speed": 10, "exp_reward": 4000, "gold_reward": 900, "min_level": 140, "max_level": 170, "drop_table": [{"item_code": "ARM_CHEST_용비늘갑", "rate": 0.08, "min_qty": 1, "max_qty": 1}, {"item_code": "ARM_SHIELD_강철방패", "rate": 0.06, "min_qty": 1, "max_qty": 1}], "attack_templates": ["고대수호자의 강력한 일격!", "고대수호자이(가) 맹렬히 공격한다!"], "death_template": "고대수호자이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 209, "name": "마룡혈족", "description": "용의 피를 이은 전사가 불타는 검을 휘두른다.", "hp": 7000, "max_hp": 7000, "attack": 130, "defense": 50, "speed": 40, "exp_reward": 5000, "gold_reward": 1200, "min_level": 160, "max_level": 200, "drop_table": [{"item_code": "WPN_SWORD_용살검", "rate": 0.05, "min_qty": 1, "max_qty": 1}, {"item_code": "ARM_CHEST_혈마갑", "rate": 0.06, "min_qty": 1, "max_qty": 1}, {"item_code": "CONS_ADVANCED_STONE", "rate": 0.04, "min_qty": 1, "max_qty": 2}], "attack_templates": ["마룡혈족의 강력한 일격!", "마룡혈족이(가) 맹렬히 공격한다!"], "death_template": "마룡혈족이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 210, "name": "뇌신의사자", "description": "천둥을 부르는 사자가 폭풍우를 몰고 온다.", "hp": 5500, "max_hp": 5500, "attack": 150, "defense": 25, "speed": 70, "exp_reward": 4500, "gold_reward": 1100, "min_level": 165, "max_level": 205, "drop_table": [{"item_code": "WPN_SPEAR_뇌정창", "rate": 0.07, "min_qty": 1, "max_qty": 1}, {"item_code": "ARM_CLOAK_마법망토", "rate": 0.06, "min_qty": 1, "max_qty": 1}], "attack_templates": ["뇌신의사자의 강력한 일격!", "뇌신의사자이(가) 맹렬히 공격한다!"], "death_template": "뇌신의사자이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 211, "name": "칠흑의기사", "description": "온몸을 칠흑 갑주로 감싼 기사가 거대한 대검을 뽑아든다.", "hp": 8000, "max_hp": 8000, "attack": 120, "defense": 55, "speed": 25, "exp_reward": 5500, "gold_reward": 1300, "min_level": 170, "max_level": 210, "drop_table": [{"item_code": "WPN_GREATSWORD_파멸대검", "rate": 0.05, "min_qty": 1, "max_qty": 1}, {"item_code": "ARM_HEAD_마수투구", "rate": 0.06, "min_qty": 1, "max_qty": 1}], "attack_templates": ["검은 기운이 대검을 감싸며 내려친다!", "칠흑의 갑주가 울리며 돌진한다!"], "death_template": "칠흑의기사이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"},
    {"id": 212, "name": "불사조의사제", "description": "불사조 깃털 장식을 두른 사제가 치유의 불꽃과 파멸의 불꽃을 동시에 다룬다.", "hp": 4500, "max_hp": 4500, "attack": 100, "defense": 35, "speed": 45, "exp_reward": 4800, "gold_reward": 1000, "min_level": 175, "max_level": 215, "drop_table": [{"item_code": "ARM_NECKLACE_용의눈물", "rate": 0.06, "min_qty": 1, "max_qty": 1}, {"item_code": "CONS_HPMP_POT", "rate": 0.1, "min_qty": 1, "max_qty": 3}], "attack_templates": ["불사조의사제의 강력한 일격!", "불사조의사제이(가) 맹렬히 공격한다!"], "death_template": "불사조의사제이(가) 쓰러지며 사라진다! (드랍 아이템 확인!)"}
    ]

    for m in monsters:
        db.add(Monster(**m))
    db.commit()
    print(f"v6.1 monsters seeded: {len(monsters)} new monsters (ID 200~212)")

if __name__ == "__main__":
    seed()
